/**
 * Shared Marketing Operations constants (channel-agnostic).
 * Facebook operator reuses TARGET_TYPES from here conceptually; operator file keeps a copy-export.
 */

export const TARGET_TYPES = Object.freeze({
  USER_ACQUISITION: 'USER_ACQUISITION',
  INVESTOR_DISCOVERY: 'INVESTOR_DISCOVERY',
});

export const OBJECTIVE_STATES = Object.freeze({
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
});

export const CHANNELS = Object.freeze({
  FACEBOOK: 'facebook',
  ZALO: 'zalo',
  QR: 'qr',
  EMAIL: 'email',
  GLOBAL_LIVE: 'global_live',
  UNKNOWN: 'unknown',
});

/** Canonical funnel events — not Facebook-only. */
export const CANONICAL_EVENTS = Object.freeze({
  CONTENT_PUBLISHED: 'CONTENT_PUBLISHED',
  SOCIAL_ENGAGEMENT: 'SOCIAL_ENGAGEMENT',
  CARDBEY_HANDOFF: 'CARDBEY_HANDOFF',
  INVESTOR_HANDOFF: 'INVESTOR_HANDOFF',
  INVESTOR_CONTACTED: 'INVESTOR_CONTACTED',
  INVESTOR_REPLY: 'INVESTOR_REPLY',
  INVESTOR_MEETING: 'INVESTOR_MEETING',
  INVESTOR_FOLLOWUP: 'INVESTOR_FOLLOWUP',
  INVESTOR_DILIGENCE: 'INVESTOR_DILIGENCE',
  INVESTOR_PASSED: 'INVESTOR_PASSED',
  INVESTOR_TERM_SHEET: 'INVESTOR_TERM_SHEET',
  INVESTOR_INVESTED: 'INVESTOR_INVESTED',
  CARDBEY_VISIT: 'CARDBEY_VISIT',
  EOI_SUBMITTED: 'EOI_SUBMITTED',
  SIGNUP: 'SIGNUP',
  BUSINESS_CREATED: 'BUSINESS_CREATED',
  BUSINESS_CLAIMED: 'BUSINESS_CLAIMED',
  BUSINESS_PUBLISHED: 'BUSINESS_PUBLISHED',
  USER_RETURNED: 'USER_RETURNED',
  /** Business Operation Intelligence (Phase A/B) — first-party analysis funnel */
  BUSINESS_ANALYSIS_STARTED: 'BUSINESS_ANALYSIS_STARTED',
  BUSINESS_CONTEXT_CONFIRMED: 'BUSINESS_CONTEXT_CONFIRMED',
  BUSINESS_SNAPSHOT_COMPLETED: 'BUSINESS_SNAPSHOT_COMPLETED',
  BUSINESS_SNAPSHOT_VIEWED: 'BUSINESS_SNAPSHOT_VIEWED',
  BUSINESS_FULL_ANALYSIS_STARTED: 'BUSINESS_FULL_ANALYSIS_STARTED',
  BUSINESS_FULL_ANALYSIS_COMPLETED: 'BUSINESS_FULL_ANALYSIS_COMPLETED',
  BUSINESS_GROWTH_PLAN_VIEWED: 'BUSINESS_GROWTH_PLAN_VIEWED',
  /** V1 pilot productization funnel */
  BUSINESS_OPERATION_LANDING_VIEWED: 'BUSINESS_OPERATION_LANDING_VIEWED',
  BUSINESS_FULL_ANALYSIS_PREVIEW_VIEWED: 'BUSINESS_FULL_ANALYSIS_PREVIEW_VIEWED',
  BUSINESS_FULL_ANALYSIS_UNLOCK_CLICKED: 'BUSINESS_FULL_ANALYSIS_UNLOCK_CLICKED',
  BUSINESS_FULL_ANALYSIS_PILOT_INTEREST: 'BUSINESS_FULL_ANALYSIS_PILOT_INTEREST',
  BUSINESS_OPERATION_FEEDBACK: 'BUSINESS_OPERATION_FEEDBACK',
  /** Legacy operator aliases kept for compatibility */
  LANDING_VISIT: 'LANDING_VISIT',
  REGISTRATION: 'REGISTRATION',
  SEVEN_DAY_RETURN: 'SEVEN_DAY_RETURN',
});

/** Events that belong to SME onboarding — never used for INVESTOR_DISCOVERY routing. */
export const SME_LIFECYCLE_EVENTS = Object.freeze([
  CANONICAL_EVENTS.EOI_SUBMITTED,
  CANONICAL_EVENTS.BUSINESS_CREATED,
  CANONICAL_EVENTS.BUSINESS_CLAIMED,
  CANONICAL_EVENTS.BUSINESS_PUBLISHED,
]);

export const EVENT_ALIASES = Object.freeze({
  SIGNUP: CANONICAL_EVENTS.SIGNUP,
  REGISTRATION: CANONICAL_EVENTS.SIGNUP,
  registration: CANONICAL_EVENTS.SIGNUP,
  EOI_SUBMITTED: CANONICAL_EVENTS.EOI_SUBMITTED,
  LANDING_VISIT: CANONICAL_EVENTS.CARDBEY_VISIT,
  CARDBEY_VISIT: CANONICAL_EVENTS.CARDBEY_VISIT,
  BUSINESS_CREATED: CANONICAL_EVENTS.BUSINESS_CREATED,
  BUSINESS_CLAIMED: CANONICAL_EVENTS.BUSINESS_CLAIMED,
  BUSINESS_PUBLISHED: CANONICAL_EVENTS.BUSINESS_PUBLISHED,
  USER_RETURNED: CANONICAL_EVENTS.USER_RETURNED,
  SEVEN_DAY_RETURN: CANONICAL_EVENTS.USER_RETURNED,
  BUSINESS_ANALYSIS_STARTED: CANONICAL_EVENTS.BUSINESS_ANALYSIS_STARTED,
  BUSINESS_CONTEXT_CONFIRMED: CANONICAL_EVENTS.BUSINESS_CONTEXT_CONFIRMED,
  BUSINESS_SNAPSHOT_COMPLETED: CANONICAL_EVENTS.BUSINESS_SNAPSHOT_COMPLETED,
  BUSINESS_SNAPSHOT_VIEWED: CANONICAL_EVENTS.BUSINESS_SNAPSHOT_VIEWED,
  BUSINESS_FULL_ANALYSIS_STARTED: CANONICAL_EVENTS.BUSINESS_FULL_ANALYSIS_STARTED,
  BUSINESS_FULL_ANALYSIS_COMPLETED: CANONICAL_EVENTS.BUSINESS_FULL_ANALYSIS_COMPLETED,
  BUSINESS_GROWTH_PLAN_VIEWED: CANONICAL_EVENTS.BUSINESS_GROWTH_PLAN_VIEWED,
  BUSINESS_OPERATION_LANDING_VIEWED: CANONICAL_EVENTS.BUSINESS_OPERATION_LANDING_VIEWED,
  BUSINESS_FULL_ANALYSIS_PREVIEW_VIEWED: CANONICAL_EVENTS.BUSINESS_FULL_ANALYSIS_PREVIEW_VIEWED,
  BUSINESS_FULL_ANALYSIS_UNLOCK_CLICKED: CANONICAL_EVENTS.BUSINESS_FULL_ANALYSIS_UNLOCK_CLICKED,
  BUSINESS_FULL_ANALYSIS_PILOT_INTEREST: CANONICAL_EVENTS.BUSINESS_FULL_ANALYSIS_PILOT_INTEREST,
  BUSINESS_OPERATION_FEEDBACK: CANONICAL_EVENTS.BUSINESS_OPERATION_FEEDBACK,
  CONTENT_PUBLISHED: CANONICAL_EVENTS.CONTENT_PUBLISHED,
  SOCIAL_ENGAGEMENT: CANONICAL_EVENTS.SOCIAL_ENGAGEMENT,
  CARDBEY_HANDOFF: CANONICAL_EVENTS.CARDBEY_HANDOFF,
  INVESTOR_HANDOFF: CANONICAL_EVENTS.INVESTOR_HANDOFF,
  INVESTOR_CONTACTED: CANONICAL_EVENTS.INVESTOR_CONTACTED,
  INVESTOR_REPLY: CANONICAL_EVENTS.INVESTOR_REPLY,
  INVESTOR_MEETING: CANONICAL_EVENTS.INVESTOR_MEETING,
  INVESTOR_FOLLOWUP: CANONICAL_EVENTS.INVESTOR_FOLLOWUP,
  INVESTOR_DILIGENCE: CANONICAL_EVENTS.INVESTOR_DILIGENCE,
  INVESTOR_PASSED: CANONICAL_EVENTS.INVESTOR_PASSED,
  INVESTOR_TERM_SHEET: CANONICAL_EVENTS.INVESTOR_TERM_SHEET,
  INVESTOR_INVESTED: CANONICAL_EVENTS.INVESTOR_INVESTED,
});

export function resolveTargetType(raw) {
  const v = String(raw || '').trim().toUpperCase();
  if (v === TARGET_TYPES.INVESTOR_DISCOVERY) return TARGET_TYPES.INVESTOR_DISCOVERY;
  return TARGET_TYPES.USER_ACQUISITION;
}

export function isInvestorDiscovery(raw) {
  return resolveTargetType(raw) === TARGET_TYPES.INVESTOR_DISCOVERY;
}

export function allowsSmeLifecycle(raw) {
  return resolveTargetType(raw) === TARGET_TYPES.USER_ACQUISITION;
}

export function normalizeCanonicalEvent(raw) {
  const key = String(raw || '').trim();
  if (!key) return null;
  if (EVENT_ALIASES[key]) return EVENT_ALIASES[key];
  const upper = key.toUpperCase();
  if (Object.values(CANONICAL_EVENTS).includes(upper)) return upper;
  return null;
}

export const DEFAULT_USER_ACQUISITION_OBJECTIVE_NAME = 'Cardbey SME user acquisition';
