/**
 * Vision intent node registry — allowed intents per entity type.
 */

import type { IntentEdge, IntentNode } from './types.js';

export const VISION_INTENT_NODES: IntentNode[] = [
  // Cardbey store
  {
    id: 'open_store',
    name: 'Open store',
    allowedEntityTypes: ['cardbey_store'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'open_url',
    agentType: 'CommerceAgent',
    clientHandled: true,
  },
  {
    id: 'order_now',
    name: 'Order now',
    allowedEntityTypes: ['cardbey_store'],
    requiredFields: ['cardbeyMatch'],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'open_store_order',
    agentType: 'CommerceAgent',
    clientHandled: true,
  },
  {
    id: 'save_store',
    name: 'Save',
    allowedEntityTypes: ['cardbey_store', 'external_business', 'service_organisation', 'event'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'save_suitcase',
    agentType: 'SuitcaseAgent',
    clientHandled: true,
  },
  {
    id: 'share_store',
    name: 'Share',
    allowedEntityTypes: ['cardbey_store', 'external_business', 'service_organisation', 'event', 'product'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'share',
    agentType: 'SuitcaseAgent',
    clientHandled: true,
  },
  {
    id: 'ask_about_store',
    name: 'Ask PIL',
    allowedEntityTypes: ['cardbey_store', 'external_business', 'service_organisation', 'product', 'event', 'unknown'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'performer_ask',
    agentType: 'PerformerAgent',
  },
  {
    id: 'contact_store',
    name: 'Contact store',
    allowedEntityTypes: ['cardbey_store'],
    requiredFields: ['phone'],
    requiredPermissions: ['authenticated'],
    riskLevel: 'medium',
    confirmationRequired: true,
    runtimeAction: 'contact_business',
    agentType: 'OutreachAgent',
  },
  // External business / service org
  {
    id: 'open_website',
    name: 'Open page',
    allowedEntityTypes: ['external_business', 'service_organisation', 'unknown', 'event', 'product'],
    requiredFields: ['resolvedUrl'],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'open_url',
    agentType: 'ResearchAgent',
    clientHandled: true,
  },
  {
    id: 'save_to_suitcase',
    name: 'Save to Suitcase',
    allowedEntityTypes: ['external_business', 'service_organisation', 'event', 'product', 'personal_contact'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'save_suitcase',
    agentType: 'SuitcaseAgent',
    clientHandled: true,
  },
  {
    id: 'create_prestore_candidate',
    name: 'Suggest adding to Cardbey',
    allowedEntityTypes: ['external_business', 'service_organisation', 'unknown'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'medium',
    confirmationRequired: true,
    runtimeAction: 'promote_discovery',
    agentType: 'DiscoveryAgent',
  },
  {
    id: 'check_if_on_cardbey',
    name: 'Check if on Cardbey',
    allowedEntityTypes: ['external_business', 'service_organisation', 'unknown'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'check_cardbey_match',
    agentType: 'DiscoveryAgent',
    clientHandled: true,
  },
  {
    id: 'compare_nearby',
    name: 'Compare nearby',
    allowedEntityTypes: ['external_business', 'service_organisation', 'cardbey_store'],
    requiredFields: ['coordinates'],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'map_compare',
    agentType: 'MapAgent',
  },
  {
    id: 'contact_business',
    name: 'Contact business',
    allowedEntityTypes: ['external_business', 'service_organisation'],
    requiredFields: ['phone'],
    requiredPermissions: ['authenticated'],
    riskLevel: 'high',
    confirmationRequired: true,
    runtimeAction: 'outreach_draft',
    agentType: 'OutreachAgent',
  },
  {
    id: 'request_offer',
    name: 'Request offer',
    allowedEntityTypes: ['external_business', 'cardbey_store'],
    requiredFields: [],
    requiredPermissions: ['authenticated'],
    riskLevel: 'medium',
    confirmationRequired: true,
    runtimeAction: 'request_offer',
    agentType: 'CommerceAgent',
  },
  // Business owner
  {
    id: 'claim_business',
    name: 'Claim business',
    allowedEntityTypes: ['external_business', 'service_organisation'],
    requiredFields: [],
    requiredPermissions: ['authenticated'],
    riskLevel: 'high',
    confirmationRequired: true,
    runtimeAction: 'claim_flow',
    agentType: 'ClaimAgent',
  },
  {
    id: 'create_store_from_scan',
    name: 'Create store from scan',
    allowedEntityTypes: ['external_business', 'service_organisation'],
    requiredFields: ['entityName'],
    requiredPermissions: ['authenticated'],
    riskLevel: 'high',
    confirmationRequired: true,
    runtimeAction: 'store_draft_from_scan',
    agentType: 'ClaimAgent',
  },
  {
    id: 'create_campaign_from_scan',
    name: 'Create campaign',
    allowedEntityTypes: ['cardbey_store', 'event', 'external_business'],
    requiredFields: [],
    requiredPermissions: ['authenticated', 'business_owner'],
    riskLevel: 'medium',
    confirmationRequired: true,
    runtimeAction: 'campaign_draft',
    agentType: 'CampaignAgent',
  },
  {
    id: 'enrich_business_profile',
    name: 'Enrich profile',
    allowedEntityTypes: ['cardbey_store', 'external_business'],
    requiredFields: [],
    requiredPermissions: ['authenticated', 'business_owner'],
    riskLevel: 'medium',
    confirmationRequired: true,
    runtimeAction: 'enrich_profile',
    agentType: 'ResearchAgent',
  },
  // Product
  {
    id: 'identify_product',
    name: 'Identify product',
    allowedEntityTypes: ['product'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'performer_ask',
    agentType: 'ResearchAgent',
  },
  {
    id: 'find_seller',
    name: 'Find seller',
    allowedEntityTypes: ['product'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'find_seller',
    agentType: 'DiscoveryAgent',
  },
  {
    id: 'add_to_store_catalog',
    name: 'Add to catalog',
    allowedEntityTypes: ['product', 'menu'],
    requiredFields: [],
    requiredPermissions: ['authenticated', 'business_owner'],
    riskLevel: 'medium',
    confirmationRequired: true,
    runtimeAction: 'catalog_draft',
    agentType: 'CatalogAgent',
  },
  // Menu
  {
    id: 'extract_menu_items',
    name: 'Extract menu items',
    allowedEntityTypes: ['menu', 'product'],
    requiredFields: ['imageAssetUrl'],
    requiredPermissions: ['authenticated'],
    riskLevel: 'medium',
    confirmationRequired: true,
    runtimeAction: 'extract_menu',
    agentType: 'CatalogAgent',
  },
  {
    id: 'create_catalog_draft',
    name: 'Create catalog draft',
    allowedEntityTypes: ['menu', 'product'],
    requiredFields: [],
    requiredPermissions: ['authenticated', 'business_owner'],
    riskLevel: 'medium',
    confirmationRequired: true,
    runtimeAction: 'catalog_draft',
    agentType: 'CatalogAgent',
  },
  {
    id: 'translate_menu',
    name: 'Translate menu',
    allowedEntityTypes: ['menu', 'product'],
    requiredFields: [],
    requiredPermissions: ['authenticated'],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'translate_menu',
    agentType: 'CatalogAgent',
  },
  // Flyer / event
  {
    id: 'create_event',
    name: 'Create event',
    allowedEntityTypes: ['event', 'flyer'],
    requiredFields: [],
    requiredPermissions: ['authenticated'],
    riskLevel: 'medium',
    confirmationRequired: true,
    runtimeAction: 'event_draft',
    agentType: 'CampaignAgent',
  },
  {
    id: 'save_event',
    name: 'Save event',
    allowedEntityTypes: ['event', 'flyer'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'save_suitcase',
    agentType: 'SuitcaseAgent',
    clientHandled: true,
  },
  // Sensitive
  {
    id: 'explain_only',
    name: 'Explain scan',
    allowedEntityTypes: ['sensitive_private', 'personal_contact'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'performer_ask',
    agentType: 'ComplianceAgent',
  },
  {
    id: 'do_not_store',
    name: 'Do not store',
    allowedEntityTypes: ['sensitive_private'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'block_storage',
    agentType: 'ComplianceAgent',
    clientHandled: true,
  },
  {
    id: 'block_acquisition',
    name: 'Blocked',
    allowedEntityTypes: ['sensitive_private'],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'block_acquisition',
    agentType: 'ComplianceAgent',
    clientHandled: true,
  },
  {
    id: 'report_wrong_result',
    name: 'Report wrong result',
    allowedEntityTypes: [
      'cardbey_store',
      'external_business',
      'service_organisation',
      'product',
      'event',
      'unknown',
      'personal_contact',
    ],
    requiredFields: [],
    requiredPermissions: [],
    riskLevel: 'low',
    confirmationRequired: false,
    runtimeAction: 'performer_report',
    agentType: 'PerformerAgent',
  },
];

export const VISION_INTENT_EDGES: IntentEdge[] = [
  { fromIntent: 'scan_external_business', toIntent: 'create_prestore_candidate', condition: 'not_on_cardbey' },
  { fromIntent: 'create_prestore_candidate', toIntent: 'enrich_business_profile', condition: 'seed_created' },
  { fromIntent: 'enrich_business_profile', toIntent: 'qa_review', condition: 'admin_pipeline' },
  { fromIntent: 'scan_menu', toIntent: 'extract_menu_items', condition: 'has_image' },
  { fromIntent: 'extract_menu_items', toIntent: 'create_catalog_draft', condition: 'owner' },
  { fromIntent: 'create_catalog_draft', toIntent: 'owner_review', condition: 'draft_ready' },
  { fromIntent: 'scan_business_card', toIntent: 'save_to_suitcase', condition: 'default' },
  { fromIntent: 'save_to_suitcase', toIntent: 'contact_business', condition: 'has_contact' },
];

const nodeById = new Map(VISION_INTENT_NODES.map((n) => [n.id, n]));

export function getIntentNode(intentId: string): IntentNode | undefined {
  return nodeById.get(intentId);
}

export function listIntentsForEntityType(entityType: string): IntentNode[] {
  return VISION_INTENT_NODES.filter((n) =>
    n.allowedEntityTypes.includes(entityType as IntentNode['allowedEntityTypes'][number]),
  );
}
