/**
 * Template catalog items by template key (cafe, restaurant, bakery, florist, food_seafood, etc.).
 * Used by buildFromTemplate for mode="template" (AI Off). Single source for new pipeline.
 * Structured templates (categories, imageQueryHints) are in structuredTemplates.js and registered here as flat item lists.
 */

import {
  TEMPLATE_FOOD_SEAFOOD,
  TEMPLATE_FOOD_RESTAURANT_GENERIC,
  TEMPLATE_FOOD_BAKERY,
  TEMPLATE_BEAUTY_NAILS,
  TEMPLATE_FASHION_BOUTIQUE,
  TEMPLATE_FASHION_KIDS,
  TEMPLATE_GAME_CENTRE,
  TEMPLATE_SERVICES_GENERIC,
  structuredItemsToFlat,
} from './structuredTemplates.js';

export const TEMPLATE_ITEMS = {
  cafe: [
    { name: 'Espresso', price: '$3.50', description: 'Rich and bold' },
    { name: 'Cappuccino', price: '$4.00', description: 'Smooth and creamy' },
    { name: 'Latte', price: '$4.50', description: 'Perfectly balanced' },
    { name: 'Americano', price: '$3.00', description: 'Classic black coffee' },
    { name: 'Mocha', price: '$4.75', description: 'Chocolate and espresso' },
    { name: 'Flat White', price: '$4.25', description: 'Velvety microfoam' },
    { name: 'Cold Brew', price: '$4.50', description: 'Smooth and refreshing' },
    { name: 'Iced Latte', price: '$5.00', description: 'Chilled and creamy' },
    { name: 'Chai Latte', price: '$4.50', description: 'Spiced tea and milk' },
    { name: 'Matcha Latte', price: '$5.25', description: 'Green tea and milk' },
    { name: 'Croissant', price: '$3.50', description: 'Buttery and flaky' },
    { name: 'Muffin', price: '$3.75', description: 'Freshly baked' },
    { name: 'Avocado Toast', price: '$9.00', description: 'Sourdough and avocado' },
    { name: 'Breakfast Wrap', price: '$8.50', description: 'Eggs and fixings' },
    { name: 'Granola Bowl', price: '$7.50', description: 'Yogurt and fruit' },
    { name: 'Smoothie', price: '$6.50', description: 'Fresh fruit blend' },
    { name: 'Fresh Juice', price: '$5.50', description: 'Cold-pressed' },
    { name: 'Hot Chocolate', price: '$4.25', description: 'Rich and sweet' },
    { name: 'Tea', price: '$3.00', description: 'Selection of teas' },
    { name: 'Bagel with Cream Cheese', price: '$4.50', description: 'Toasted to order' },
    { name: 'Quiche Slice', price: '$6.00', description: 'Daily special' },
    { name: 'Soup of the Day', price: '$5.50', description: 'Homemade' },
    { name: 'Sandwich', price: '$9.50', description: 'Build your own' },
    { name: 'Salad Bowl', price: '$10.00', description: 'Fresh greens' },
    { name: 'Cookie', price: '$2.50', description: 'House-made' },
    { name: 'Brownie', price: '$3.50', description: 'Chocolate fudge' },
    { name: 'Cake Slice', price: '$5.00', description: 'Daily selection' },
    { name: 'Energy Bar', price: '$3.25', description: 'Nutrient-packed' },
    { name: 'Bottled Water', price: '$2.50', description: 'Still or sparkling' },
    { name: 'Soft Drink', price: '$2.75', description: 'Various options' },
  ],
  restaurant: [
    { name: 'Signature Burger', price: '$15.00', description: 'Our house special' },
    { name: 'Caesar Salad', price: '$12.00', description: 'Fresh and crisp' },
    { name: 'Pasta Carbonara', price: '$18.00', description: 'Creamy and delicious' },
    { name: 'Margherita Pizza', price: '$14.00', description: 'Classic Italian' },
    { name: 'Grilled Salmon', price: '$22.00', description: 'With seasonal vegetables' },
    { name: 'Ribeye Steak', price: '$28.00', description: '12oz, cooked to order' },
    { name: 'Chicken Parmesan', price: '$16.00', description: 'Crispy and saucy' },
    { name: 'Fish and Chips', price: '$14.50', description: 'Beer-battered' },
    { name: 'Vegetable Stir Fry', price: '$13.00', description: 'Wok-tossed' },
    { name: 'Soup of the Day', price: '$7.00', description: "Chef's choice" },
    { name: 'Garlic Bread', price: '$5.00', description: 'Toasted with herbs' },
    { name: 'Mozzarella Sticks', price: '$8.00', description: 'With marinara' },
    { name: 'Wings', price: '$11.00', description: 'Choice of sauce' },
    { name: 'Club Sandwich', price: '$12.00', description: 'Triple-decker' },
    { name: 'Club Salad', price: '$11.00', description: 'Grilled chicken' },
    { name: 'Kids Meal', price: '$8.00', description: 'Choice of entrée' },
    { name: 'Tiramisu', price: '$8.50', description: 'Classic dessert' },
    { name: 'Chocolate Lava Cake', price: '$9.00', description: 'Warm and gooey' },
    { name: 'Ice Cream', price: '$5.50', description: 'Two scoops' },
    { name: 'Cheesecake', price: '$8.00', description: 'New York style' },
    { name: 'Coffee', price: '$3.50', description: 'Regular or decaf' },
    { name: 'Iced Tea', price: '$3.00', description: 'Sweet or unsweet' },
    { name: 'Lemonade', price: '$3.50', description: 'Fresh squeezed' },
    { name: 'Wine', price: '$8.00', description: 'House selection' },
    { name: 'Beer', price: '$6.00', description: 'Draft or bottle' },
    { name: 'Cocktail', price: '$10.00', description: 'Classic or signature' },
    { name: 'Dessert Special', price: '$7.50', description: 'Ask your server' },
    { name: 'Side Salad', price: '$4.00', description: 'Garden fresh' },
    { name: 'French Fries', price: '$4.50', description: 'Crispy golden' },
    { name: 'Coleslaw', price: '$3.50', description: 'Creamy or vinegar' },
  ],
  food_seafood: structuredItemsToFlat(TEMPLATE_FOOD_SEAFOOD.items),
  food_restaurant_generic: structuredItemsToFlat(TEMPLATE_FOOD_RESTAURANT_GENERIC.items),
  food_bakery: structuredItemsToFlat(TEMPLATE_FOOD_BAKERY.items),
  beauty_nails: structuredItemsToFlat(TEMPLATE_BEAUTY_NAILS.items),
  fashion_boutique: structuredItemsToFlat(TEMPLATE_FASHION_BOUTIQUE.items),
  fashion_kids: structuredItemsToFlat(TEMPLATE_FASHION_KIDS.items),
  game_centre: structuredItemsToFlat(TEMPLATE_GAME_CENTRE.items),
  services_generic: structuredItemsToFlat(TEMPLATE_SERVICES_GENERIC.items),
  bakery: [
    { name: 'Croissant', price: '$3.00', description: 'Buttery and flaky' },
    { name: 'Chocolate Cake', price: '$8.00', description: 'Rich and decadent' },
    { name: 'Sourdough Bread', price: '$6.00', description: 'Freshly baked daily' },
    { name: 'Apple Pie', price: '$5.00', description: 'Homemade with love' },
    { name: 'Cinnamon Roll', price: '$4.50', description: 'Cream cheese frosting' },
    { name: 'Muffin', price: '$3.50', description: 'Blueberry or chocolate' },
    { name: 'Bagel', price: '$2.75', description: 'Toasted with spread' },
    { name: 'Danish', price: '$4.00', description: 'Fruit or cheese' },
    { name: 'Scone', price: '$3.75', description: 'Plain or fruit' },
    { name: 'Brownie', price: '$3.25', description: 'Fudge or blondie' },
    { name: 'Cookie', price: '$2.50', description: 'Chocolate chip or oatmeal' },
    { name: 'Éclair', price: '$4.50', description: 'Chocolate or coffee' },
    { name: 'Macaron', price: '$2.00', description: 'Assorted flavours' },
    { name: 'Cupcake', price: '$3.50', description: 'Daily flavours' },
    { name: 'Loaf Cake', price: '$7.00', description: 'Banana or lemon' },
    { name: 'Tart', price: '$5.50', description: 'Fruit or custard' },
    { name: 'Baguette', price: '$4.00', description: 'Fresh daily' },
    { name: 'Focaccia', price: '$5.00', description: 'Herb or olive' },
    { name: 'Pie Slice', price: '$4.50', description: 'Seasonal selection' },
    { name: 'Cheese Danish', price: '$4.25', description: 'Cream cheese filled' },
    { name: 'Palmier', price: '$3.00', description: 'Crispy caramelized' },
    { name: 'Bread Pudding', price: '$5.00', description: 'Warm with sauce' },
    { name: 'Strudel', price: '$4.75', description: 'Apple or cherry' },
    { name: 'Donut', price: '$2.75', description: 'Glazed or filled' },
    { name: 'Biscotti', price: '$3.00', description: 'Almond or chocolate' },
    { name: 'Shortbread', price: '$3.25', description: 'Buttery and crisp' },
    { name: 'Bundt Cake Slice', price: '$4.00', description: 'Lemon or chocolate' },
    { name: 'Pavlova', price: '$6.00', description: 'Berry and cream' },
    { name: 'Bread Roll', price: '$1.50', description: 'White or whole grain' },
    { name: 'Coffee', price: '$3.00', description: 'To go with your pastry' },
  ],
  florist: [
    { name: 'Mixed Bouquet', price: '$35.00', description: 'Fresh seasonal flowers' },
    { name: 'Rose Arrangement', price: '$45.00', description: 'Classic red or mixed roses' },
    { name: 'Sympathy Wreath', price: '$55.00', description: 'Elegant tribute arrangement' },
    { name: 'Wedding Centerpiece', price: '$75.00', description: 'Custom table arrangement' },
    { name: 'Hand-tied Bouquet', price: '$40.00', description: 'Garden-style bouquet' },
    { name: 'Succulent Planter', price: '$25.00', description: 'Low-maintenance gift' },
    { name: 'Dried Flower Bundle', price: '$30.00', description: 'Long-lasting display' },
    { name: 'Seasonal Posy', price: '$28.00', description: 'Local seasonal blooms' },
    { name: 'Tulip Bouquet', price: '$32.00', description: 'Bright spring colours' },
    { name: 'Lily Arrangement', price: '$38.00', description: 'Elegant and fragrant' },
    { name: 'Sunflower Bundle', price: '$30.00', description: 'Cheerful and bold' },
    { name: 'Orchid Plant', price: '$45.00', description: 'Potted, easy care' },
    { name: 'Corsage', price: '$25.00', description: 'For special events' },
    { name: 'Boutonnière', price: '$15.00', description: 'Single stem' },
    { name: 'Table Centerpiece', price: '$65.00', description: 'Event styling' },
    { name: 'Baby Breath Bundle', price: '$20.00', description: 'Delicate filler' },
    { name: 'Hydrangea Bouquet', price: '$42.00', description: 'Full and lush' },
    { name: 'Peony Arrangement', price: '$50.00', description: 'Romantic blooms' },
    { name: 'Daisy Bouquet', price: '$22.00', description: 'Simple and fresh' },
    { name: 'Carnation Bundle', price: '$18.00', description: 'Long-lasting colour' },
    { name: 'Greenery Bundle', price: '$25.00', description: 'Eucalyptus and foliage' },
    { name: 'Vase', price: '$15.00', description: 'Glass or ceramic' },
    { name: 'Gift Card', price: '$25.00', description: 'Any amount' },
    { name: 'Delivery', price: '$12.00', description: 'Same-day available' },
    { name: 'Subscription', price: '$35.00', description: 'Weekly or monthly' },
    { name: 'Custom Arrangement', price: '$55.00', description: 'Consultation included' },
    { name: 'Single Stem Rose', price: '$8.00', description: 'Red, white, or mixed' },
    { name: 'Lavender Bundle', price: '$20.00', description: 'Dried, fragrant' },
    { name: 'Wildflower Bouquet', price: '$28.00', description: 'Local and seasonal' },
    { name: 'Jasmine Plant', price: '$32.00', description: 'Potted, fragrant' },
    { name: 'Herb Garden', price: '$28.00', description: 'Culinary herbs' },
    { name: 'Cactus Arrangement', price: '$35.00', description: 'Desert style' },
  ],
  nail_salon: [
    { name: 'Classic Manicure', price: '$42.00', description: 'Shape, cuticle care, polish' },
    { name: 'Gel Manicure', price: '$55.00', description: 'Long-lasting gel polish' },
    { name: 'Acrylic Full Set', price: '$65.00', description: 'Full set with tips' },
    { name: 'Classic Pedicure', price: '$52.00', description: 'Soak, exfoliate, polish' },
    { name: 'Gel Pedicure', price: '$65.00', description: 'Gel polish on toes' },
    { name: 'Spa Pedicure', price: '$75.00', description: 'Extended soak and massage' },
    { name: 'Nail Art', price: '$10.00', description: 'Design per nail' },
    { name: 'Nail Repair', price: '$8.00', description: 'Single nail repair' },
    { name: 'Lash Lift', price: '$65.00', description: 'Lash lift and tint' },
    { name: 'Brow Lamination', price: '$45.00', description: 'Brow shape and set' },
    { name: 'Waxing - Brows', price: '$18.00', description: 'Brow wax' },
    { name: 'Waxing - Lip', price: '$12.00', description: 'Lip wax' },
    { name: 'Waxing - Full Leg', price: '$45.00', description: 'Full leg wax' },
    { name: 'Gel Removal', price: '$15.00', description: 'Soak-off gel removal' },
    { name: 'Nail Shape & File', price: '$12.00', description: 'Shape and buff' },
    { name: 'Cuticle Oil Treatment', price: '$8.00', description: 'Nourishing cuticle oil' },
    { name: 'Paraffin Wax Hands', price: '$20.00', description: 'Hand moisturising treatment' },
    { name: 'Hand Massage', price: '$15.00', description: '10 min hand massage' },
    { name: 'Kids Manicure', price: '$25.00', description: 'Quick polish for kids' },
    { name: 'Bridal Package', price: '$120.00', description: 'Manicure and pedicure' },
    { name: 'Shellac Manicure', price: '$50.00', description: 'CND Shellac' },
    { name: 'French Manicure', price: '$48.00', description: 'Classic French tips' },
    { name: 'Ombre Nails', price: '$55.00', description: 'Ombre colour blend' },
    { name: 'Nail Extension', price: '$70.00', description: 'Single extension' },
    { name: 'Facial - Express', price: '$45.00', description: '30 min express facial' },
    { name: 'Facial - Full', price: '$85.00', description: '60 min full facial' },
    { name: 'Eyebrow Tint', price: '$15.00', description: 'Brow tint' },
    { name: 'Eyelash Tint', price: '$18.00', description: 'Lash tint' },
    { name: 'Gift Voucher', price: '$50.00', description: 'Any amount' },
    { name: 'Consultation', price: '$0.00', description: 'Free 15 min consult' },
  ],
  retail: [
    { name: 'Women\'s Blouse', price: '$45.00', description: 'Classic fit, multiple colours' },
    { name: 'High-Waist Trousers', price: '$65.00', description: 'Tailored, office-ready' },
    { name: 'Summer Dress', price: '$89.00', description: 'Light and breezy' },
    { name: 'Denim Jacket', price: '$75.00', description: 'Casual layering piece' },
    { name: 'Knit Sweater', price: '$55.00', description: 'Soft and warm' },
    { name: 'Leather Handbag', price: '$120.00', description: 'Everyday carry' },
    { name: 'Ankle Boots', price: '$95.00', description: 'Comfortable heel' },
    { name: 'Silk Scarf', price: '$35.00', description: 'Printed design' },
    { name: 'Statement Necklace', price: '$42.00', description: 'Handcrafted' },
    { name: 'Sunglasses', price: '$55.00', description: 'UV protection' },
    { name: 'Belts', price: '$28.00', description: 'Leather or fabric' },
    { name: 'T-Shirt', price: '$25.00', description: 'Premium cotton' },
    { name: 'Skirt', price: '$48.00', description: 'Mid-length, versatile' },
    { name: 'Cardigan', price: '$52.00', description: 'Button-front' },
    { name: 'Jumpsuit', price: '$78.00', description: 'One-piece style' },
    { name: 'Winter Coat', price: '$145.00', description: 'Warm and stylish' },
    { name: 'Earrings', price: '$22.00', description: 'Stud or drop' },
    { name: 'Watch', price: '$85.00', description: 'Classic or sport' },
    { name: 'Wallet', price: '$38.00', description: 'Compact and secure' },
    { name: 'Hair Accessories', price: '$15.00', description: 'Clips and bands' },
    { name: 'Leggings', price: '$32.00', description: 'High-waist, stretch' },
    { name: 'Shorts', price: '$35.00', description: 'Casual or tailored' },
    { name: 'Polo Shirt', price: '$30.00', description: 'Men\'s or women\'s' },
    { name: 'Hoodie', price: '$45.00', description: 'Cozy fleece' },
    { name: 'Trainers', price: '$72.00', description: 'Everyday sneakers' },
    { name: 'Sandals', price: '$42.00', description: 'Summer footwear' },
    { name: 'Pajama Set', price: '$48.00', description: 'Comfortable sleepwear' },
    { name: 'Swimwear', price: '$55.00', description: 'One or two piece' },
    { name: 'Gift Card', price: '$50.00', description: 'Any amount' },
    { name: 'Personal Styling', price: '$0.00', description: 'Free consultation' },
  ],
  generic_store: [
    { name: 'Service 1', price: '$25.00', description: 'Main service' },
    { name: 'Service 2', price: '$35.00', description: 'Standard option' },
    { name: 'Service 3', price: '$45.00', description: 'Premium option' },
    { name: 'Consultation', price: '$0.00', description: 'Free assessment' },
    { name: 'Package A', price: '$80.00', description: 'Bundle of services' },
    { name: 'Package B', price: '$120.00', description: 'Value bundle' },
    { name: 'Add-on 1', price: '$15.00', description: 'Optional extra' },
    { name: 'Add-on 2', price: '$20.00', description: 'Optional extra' },
    { name: 'Gift Voucher', price: '$50.00', description: 'Any amount' },
    { name: 'Membership', price: '$99.00', description: 'Monthly benefits' },
    { name: 'Workshop', price: '$65.00', description: 'Group session' },
    { name: 'One-on-one', price: '$75.00', description: 'Private session' },
    { name: 'Follow-up', price: '$30.00', description: 'Return visit' },
    { name: 'Intro Offer', price: '$40.00', description: 'First-time discount' },
    { name: 'Seasonal Special', price: '$55.00', description: 'Limited time' },
    { name: 'Item A', price: '$22.00', description: 'Quality product' },
    { name: 'Item B', price: '$28.00', description: 'Popular choice' },
    { name: 'Item C', price: '$32.00', description: 'Best value' },
    { name: 'Custom', price: '$0.00', description: 'Quote on request' },
    { name: 'Basic', price: '$19.00', description: 'Essential option' },
    { name: 'Standard', price: '$29.00', description: 'Most popular' },
    { name: 'Premium', price: '$49.00', description: 'Full experience' },
    { name: 'Express', price: '$24.00', description: 'Quick service' },
    { name: 'Deluxe', price: '$59.00', description: 'Top tier' },
    { name: 'Starter', price: '$15.00', description: 'Entry level' },
    { name: 'Professional', price: '$85.00', description: 'Expert level' },
    { name: 'Maintenance', price: '$35.00', description: 'Ongoing care' },
    { name: 'Gift Card', price: '$50.00', description: 'Any amount' },
    { name: 'Booking', price: '$0.00', description: 'Reserve your spot' },
  ],
};

const TARGET_ITEM_COUNT = 30;
const MIN_ITEM_COUNT = 24;
const MAX_ITEM_COUNT = 36;

/** Valid template keys for mode=template (must have entry in TEMPLATE_ITEMS). */
export function getTemplateItems(templateKey) {
  const key = (templateKey && String(templateKey).toLowerCase().trim()) || '';
  return TEMPLATE_ITEMS[key] || null;
}

/**
 * Expand template items to meet target count (24–36). Used for free/template path so stores get ~30 items.
 * If list has fewer than MIN_ITEM_COUNT, append variations (same template family) until target.
 * @param {string} templateKey
 * @param {number} [target]
 * @returns {{ name: string, description?: string, price?: string }[]}
 */
export function expandTemplateItems(templateKey, target = TARGET_ITEM_COUNT) {
  const list = getTemplateItems(templateKey);
  if (!list || !Array.isArray(list)) return list || [];
  const cap = Math.min(MAX_ITEM_COUNT, Math.max(MIN_ITEM_COUNT, target));
  if (list.length >= cap) return list.slice(0, cap);
  if (list.length >= MIN_ITEM_COUNT) return list.slice(0, cap);
  const out = [...list];
  const variants = [' (Variation)', ' - Style B', ' - Option 2', ' - Alt', ' - Second'];
  let i = 0;
  while (out.length < MIN_ITEM_COUNT && list.length > 0) {
    const base = list[i % list.length];
    const v = variants[Math.floor(i / list.length) % variants.length];
    out.push({
      name: (base.name || '').replace(/\s*\([^)]*\)$/, '') + v,
      description: base.description,
      price: base.price,
    });
    i++;
  }
  return out.slice(0, cap);
}
