/**
 * Intent routing categories and pattern rules.
 * Used by intentRouter and endpoint audit tooling.
 */

/** @typedef {'AGENT_WORKFLOW'|'USER_ACTION'|'CONTENT_CRUD'|'SOCIAL'|'TRANSACTION'|'HYBRID'|'READ_ONLY'|'OBSERVE'|'ADMIN'|'UNKNOWN'} IntentCategory */

/** @typedef {'kernel'|'direct'|'hybrid'} ExecutionPath */

export const EXECUTION_PATH_BY_CATEGORY = {
  AGENT_WORKFLOW: 'kernel',
  USER_ACTION: 'direct',
  CONTENT_CRUD: 'direct',
  SOCIAL: 'direct',
  TRANSACTION: 'direct',
  HYBRID: 'hybrid',
  READ_ONLY: 'direct',
  OBSERVE: 'direct',
  ADMIN: 'direct',
  UNKNOWN: 'direct',
};

export const CATEGORY_RULES = {
  AGENT_WORKFLOW: [
    'analyze',
    'generate',
    'create_campaign',
    'launch',
    'optimize',
    'plan',
    'strategy',
    'recommend',
    'insights',
    'forecast',
    'orchestrator',
    'intake',
    'proactive-step',
    'runtime/missions',
    'passive-generation',
    'automation',
    'configure-from-photo',
    'researcher',
    'ai-operator',
    'intent-graph',
    'extract-card',
    'ingest-document',
    'vision',
  ],
  USER_ACTION: [
    'profile',
    'account',
    'settings',
    'preferences',
    'avatar',
    'password',
    'email',
    'notification',
    'theme',
    '/auth/',
    '/users/me',
    '/oauth/',
  ],
  CONTENT_CRUD: [
    'upload',
    'download',
    'save_draft',
    'delete_draft',
    'edit_product',
    'update_inventory',
    'add_image',
    'remove_image',
    '/draft-store',
    '/store-draft',
    '/contents',
    '/content-library',
    '/assets',
    '/products',
    '/creative-templates',
    '/greeting-cards',
    '/playlists',
    '/artifacts',
    '/docs',
    '/suitcase',
    '/cards',
  ],
  SOCIAL: [
    'like',
    'comment',
    'share',
    'follow',
    'unfollow',
    'report',
    'block',
    'mute',
    'subscribe',
    'content-interactions',
    '/threads',
    '/chat/threads',
  ],
  TRANSACTION: [
    'order',
    'checkout',
    'payment',
    'refund',
    'invoice',
    'cart',
    'purchase',
    '/billing',
    '/promo/engine',
    '/loyalty',
    '/reward',
    '/promos',
    '/promotions',
  ],
  HYBRID: [
    'publish',
    'delete',
    'archive',
    'restore',
    'moderate',
    'approve',
    'reject',
    'schedule',
    'commit',
    'apply-schedule',
    'build-playlist',
    'generate-channel',
  ],
  READ_ONLY: [
    '/health',
    '/healthz',
    '/readyz',
    '/storefront',
    '/public/',
    '/stream',
  ],
  OBSERVE: [
    '/pil/events',
    '/telemetry',
    '/intelligence/metrics',
  ],
  ADMIN: [
    '/admin/',
    '/self-healing',
    '/control-tower',
    '/ops/',
    '/internal/',
  ],
};

/** @param {IntentCategory} category */
export function executionPathForCategory(category) {
  return EXECUTION_PATH_BY_CATEGORY[category] ?? 'direct';
}
