/**
 * Accounting Documents V1 — constants + status machines.
 */

export const DOC_TYPE = Object.freeze({
  QUOTE: 'QUOTE',
  INVOICE: 'INVOICE',
  CREDIT_NOTE: 'CREDIT_NOTE',
  PURCHASE_ORDER: 'PURCHASE_ORDER',
  RECEIPT: 'RECEIPT',
});

export const QUOTE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  READY: 'READY',
  ISSUED: 'ISSUED',
  VIEWED: 'VIEWED',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  EXPIRED: 'EXPIRED',
  CONVERTED: 'CONVERTED',
  CANCELLED: 'CANCELLED',
});

export const INVOICE_STATUS = Object.freeze({
  DRAFT: 'DRAFT',
  ISSUED: 'ISSUED',
  VIEWED: 'VIEWED',
  PAID: 'PAID',
  PART_PAID: 'PART_PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED',
});

export const V1_QUOTE_TYPES = new Set([DOC_TYPE.QUOTE]);
export const V1_INVOICE_TYPES = new Set([DOC_TYPE.INVOICE]);

export const ACCOUNTING_EVENTS = Object.freeze({
  QUOTE_CREATED: 'QUOTE_CREATED',
  QUOTE_UPDATED: 'QUOTE_UPDATED',
  QUOTE_ISSUED: 'QUOTE_ISSUED',
  QUOTE_VIEWED: 'QUOTE_VIEWED',
  QUOTE_ACCEPTED: 'QUOTE_ACCEPTED',
  QUOTE_DECLINED: 'QUOTE_DECLINED',
  QUOTE_CONVERTED: 'QUOTE_CONVERTED',
  INVOICE_CREATED: 'INVOICE_CREATED',
  INVOICE_ISSUED: 'INVOICE_ISSUED',
  INVOICE_VIEWED: 'INVOICE_VIEWED',
  INVOICE_MARKED_PAID: 'INVOICE_MARKED_PAID',
  INVOICE_CANCELLED: 'INVOICE_CANCELLED',
  DOCUMENT_DOWNLOADED: 'DOCUMENT_DOWNLOADED',
  DOCUMENT_SENT: 'DOCUMENT_SENT',
});
