/**
 * Creator Publishing Center — canonical status, types, and transition rules.
 */

export const CREATOR_PUBLISHING_STATUS = Object.freeze({
  DRAFT: 'draft',
  OWNER_REVIEW: 'owner_review',
  CLASSIFICATION_PENDING: 'classification_pending',
  AI_REVIEWED: 'ai_reviewed',
  HUMAN_REVIEW_REQUIRED: 'human_review_required',
  READY_TO_PUBLISH: 'ready_to_publish',
  SCHEDULED: 'scheduled',
  PUBLISHED: 'published',
  CHANGES_REQUESTED: 'changes_requested',
  REJECTED: 'rejected',
  ESCALATED: 'escalated',
  ARCHIVED: 'archived',
  FAILED: 'failed',
  DELETED: 'deleted',
});

/** @deprecated use REJECTED */
export const LEGACY_FAILED = CREATOR_PUBLISHING_STATUS.FAILED;

export const CREATOR_PUBLISHABLE_TYPES = Object.freeze({
  VIDEO: 'VIDEO',
  ARTICLE: 'ARTICLE',
  LIVESTREAM: 'LIVESTREAM',
  CREATOR_SERVICE: 'CREATOR_SERVICE',
  DIGITAL_PRODUCT: 'DIGITAL_PRODUCT',
});

export const CLASSIFICATION_RECOMMENDATION = Object.freeze({
  READY_TO_PUBLISH: 'READY_TO_PUBLISH',
  HUMAN_REVIEW_REQUIRED: 'HUMAN_REVIEW_REQUIRED',
  CHANGES_REQUESTED: 'CHANGES_REQUESTED',
  REJECT: 'REJECT',
  ESCALATE: 'ESCALATE',
});

export const PUBLISHING_DESTINATIONS = Object.freeze({
  CREATOR_PROFILE: 'CREATOR_PROFILE',
  CREATOR_FEED: 'CREATOR_FEED',
  MARKETPLACE: 'MARKETPLACE',
  BUSINESS_DISCOVERY: 'BUSINESS_DISCOVERY',
  SEARCH: 'SEARCH',
  RECOMMENDATIONS: 'RECOMMENDATIONS',
});

export const QUEUE_FILTERS = Object.freeze({
  PENDING_CLASSIFICATION: 'pending_classification',
  HUMAN_REVIEW: 'human_review_required',
  AI_FLAGGED: 'ai_flagged',
  READY: 'ready_to_publish',
  SCHEDULED: 'scheduled',
  PUBLISHED: 'published',
  CHANGES_REQUESTED: 'changes_requested',
  REJECTED: 'rejected',
  ESCALATED: 'escalated',
});

export const QUEUE_STATUS_MAP = Object.freeze({
  [QUEUE_FILTERS.PENDING_CLASSIFICATION]: [
    CREATOR_PUBLISHING_STATUS.OWNER_REVIEW,
    CREATOR_PUBLISHING_STATUS.CLASSIFICATION_PENDING,
  ],
  [QUEUE_FILTERS.HUMAN_REVIEW]: [CREATOR_PUBLISHING_STATUS.HUMAN_REVIEW_REQUIRED],
  [QUEUE_FILTERS.AI_FLAGGED]: [CREATOR_PUBLISHING_STATUS.AI_REVIEWED, CREATOR_PUBLISHING_STATUS.ESCALATED],
  [QUEUE_FILTERS.READY]: [CREATOR_PUBLISHING_STATUS.READY_TO_PUBLISH],
  [QUEUE_FILTERS.SCHEDULED]: [CREATOR_PUBLISHING_STATUS.SCHEDULED],
  [QUEUE_FILTERS.PUBLISHED]: [CREATOR_PUBLISHING_STATUS.PUBLISHED],
  [QUEUE_FILTERS.CHANGES_REQUESTED]: [CREATOR_PUBLISHING_STATUS.CHANGES_REQUESTED],
  [QUEUE_FILTERS.REJECTED]: [CREATOR_PUBLISHING_STATUS.REJECTED, CREATOR_PUBLISHING_STATUS.FAILED],
  [QUEUE_FILTERS.ESCALATED]: [CREATOR_PUBLISHING_STATUS.ESCALATED],
});

export const MODEL_VERSION = 'creator-classifier-v1';
export const POLICY_VERSION = 'creator-publishing-policy-v1';

/** Release one: never auto-publish */
export const AUTO_PUBLISH_ENABLED = false;

const ALLOWED_TRANSITIONS = Object.freeze({
  [CREATOR_PUBLISHING_STATUS.DRAFT]: [CREATOR_PUBLISHING_STATUS.OWNER_REVIEW, CREATOR_PUBLISHING_STATUS.DELETED],
  [CREATOR_PUBLISHING_STATUS.OWNER_REVIEW]: [
    CREATOR_PUBLISHING_STATUS.CLASSIFICATION_PENDING,
    CREATOR_PUBLISHING_STATUS.DRAFT,
  ],
  [CREATOR_PUBLISHING_STATUS.CLASSIFICATION_PENDING]: [
    CREATOR_PUBLISHING_STATUS.AI_REVIEWED,
    CREATOR_PUBLISHING_STATUS.HUMAN_REVIEW_REQUIRED,
  ],
  [CREATOR_PUBLISHING_STATUS.AI_REVIEWED]: [
    CREATOR_PUBLISHING_STATUS.READY_TO_PUBLISH,
    CREATOR_PUBLISHING_STATUS.HUMAN_REVIEW_REQUIRED,
    CREATOR_PUBLISHING_STATUS.CHANGES_REQUESTED,
    CREATOR_PUBLISHING_STATUS.ESCALATED,
  ],
  [CREATOR_PUBLISHING_STATUS.HUMAN_REVIEW_REQUIRED]: [
    CREATOR_PUBLISHING_STATUS.READY_TO_PUBLISH,
    CREATOR_PUBLISHING_STATUS.CHANGES_REQUESTED,
    CREATOR_PUBLISHING_STATUS.REJECTED,
    CREATOR_PUBLISHING_STATUS.ESCALATED,
    CREATOR_PUBLISHING_STATUS.CLASSIFICATION_PENDING,
  ],
  [CREATOR_PUBLISHING_STATUS.READY_TO_PUBLISH]: [
    CREATOR_PUBLISHING_STATUS.PUBLISHED,
    CREATOR_PUBLISHING_STATUS.SCHEDULED,
    CREATOR_PUBLISHING_STATUS.HUMAN_REVIEW_REQUIRED,
  ],
  [CREATOR_PUBLISHING_STATUS.SCHEDULED]: [
    CREATOR_PUBLISHING_STATUS.PUBLISHED,
    CREATOR_PUBLISHING_STATUS.READY_TO_PUBLISH,
  ],
  [CREATOR_PUBLISHING_STATUS.CHANGES_REQUESTED]: [CREATOR_PUBLISHING_STATUS.DRAFT],
  [CREATOR_PUBLISHING_STATUS.REJECTED]: [CREATOR_PUBLISHING_STATUS.DRAFT],
  [CREATOR_PUBLISHING_STATUS.FAILED]: [CREATOR_PUBLISHING_STATUS.DRAFT],
  [CREATOR_PUBLISHING_STATUS.ESCALATED]: [
    CREATOR_PUBLISHING_STATUS.HUMAN_REVIEW_REQUIRED,
    CREATOR_PUBLISHING_STATUS.REJECTED,
    CREATOR_PUBLISHING_STATUS.READY_TO_PUBLISH,
  ],
});

/**
 * @param {string} from
 * @param {string} to
 */
export function canTransitionPublishingStatus(from, to) {
  const normalizedFrom = normalizePublishingStatus(from);
  const normalizedTo = normalizePublishingStatus(to);
  if (normalizedFrom === normalizedTo) return true;
  const allowed = ALLOWED_TRANSITIONS[normalizedFrom];
  return Array.isArray(allowed) && allowed.includes(normalizedTo);
}

/**
 * @param {string} status
 */
export function normalizePublishingStatus(status) {
  const value = String(status || '').toLowerCase();
  if (value === CREATOR_PUBLISHING_STATUS.FAILED) return CREATOR_PUBLISHING_STATUS.REJECTED;
  return value;
}

/**
 * @param {string} recommendation
 * @param {object} [risk]
 */
export function routeStatusAfterClassification(recommendation, risk = {}) {
  const overall = risk.overall || 'LOW';
  switch (recommendation) {
    case CLASSIFICATION_RECOMMENDATION.READY_TO_PUBLISH:
      return overall === 'CRITICAL' || overall === 'HIGH'
        ? CREATOR_PUBLISHING_STATUS.ESCALATED
        : CREATOR_PUBLISHING_STATUS.READY_TO_PUBLISH;
    case CLASSIFICATION_RECOMMENDATION.HUMAN_REVIEW_REQUIRED:
      return CREATOR_PUBLISHING_STATUS.HUMAN_REVIEW_REQUIRED;
    case CLASSIFICATION_RECOMMENDATION.CHANGES_REQUESTED:
      return CREATOR_PUBLISHING_STATUS.HUMAN_REVIEW_REQUIRED;
    case CLASSIFICATION_RECOMMENDATION.REJECT:
      return CREATOR_PUBLISHING_STATUS.ESCALATED;
    case CLASSIFICATION_RECOMMENDATION.ESCALATE:
      return CREATOR_PUBLISHING_STATUS.ESCALATED;
    default:
      return CREATOR_PUBLISHING_STATUS.HUMAN_REVIEW_REQUIRED;
  }
}

export const DEFAULT_PUBLISHING_DESTINATIONS = [
  PUBLISHING_DESTINATIONS.CREATOR_PROFILE,
  PUBLISHING_DESTINATIONS.CREATOR_FEED,
  PUBLISHING_DESTINATIONS.SEARCH,
];

export default {
  CREATOR_PUBLISHING_STATUS,
  CREATOR_PUBLISHABLE_TYPES,
  CLASSIFICATION_RECOMMENDATION,
  PUBLISHING_DESTINATIONS,
  QUEUE_FILTERS,
  QUEUE_STATUS_MAP,
  AUTO_PUBLISH_ENABLED,
  canTransitionPublishingStatus,
  normalizePublishingStatus,
  routeStatusAfterClassification,
};
