/** Default action labels for platform activity events (Control Center quick routing). */
export const EVENT_TYPE_ACTION_LABEL = {
  business_seed_created: 'Open QA Review',
  business_seed_qa_approved: 'Open QA Review',
  business_seed_rejected: 'Open QA Review',
  business_claim_started: 'Open Claims',
  business_claim_verified: 'Open Claims',
  business_activated: 'Open Discovery',
  user_registered: 'Open Accounts',
  user_email_verified: 'Open Accounts',
  business_owner_created: 'Open Accounts',
  account_verification_failed: 'Open Accounts',
  draft_store_created: 'Open Store Network',
  draft_store_reviewed: 'Open Store Network',
  store_published: 'Open Store Network',
  business_space_published: 'Open Store Network',
  discovery_seed_converted_to_store: 'Open Discovery',
  store_activation_failed: 'Open Store Network',
  performer_session_started: 'Open Runtime',
  mission_started: 'Open Runtime',
  mission_blocked: 'Open Runtime',
  mission_completed: 'Open Runtime',
  mission_failed: 'Open Runtime',
  device_pair_requested: 'Open Devices',
  device_paired: 'Open Devices',
  device_online: 'Open Devices',
  device_offline: 'Open Devices',
  playlist_started: 'Open Devices',
  playlist_failed: 'Open Devices',
  heartbeat_missing: 'Open Devices',
  deployment_detected: 'Open Control Tower',
  api_error_spike: 'Open Control Tower',
  queue_backlog: 'Open Control Tower',
  admin_qa_action: 'Open QA Review',
  data_source_ingest_completed: 'Open Data Sources',
};
