/** Default routes when emit() omits route — Control Center command layer. */
export const EVENT_TYPE_DEFAULT_ROUTE = {
  business_seed_created: '/admin/discovery?view=qa',
  business_seed_qa_approved: '/admin/discovery?view=qa',
  business_seed_rejected: '/admin/discovery?view=qa',
  business_claim_started: '/admin/discovery',
  business_claim_verified: '/admin/discovery',
  business_activated: '/admin/discovery',
  user_registered: '/admin',
  user_email_verified: '/admin',
  business_owner_created: '/admin',
  account_verification_failed: '/admin',
  draft_store_created: '/marketing#store-network',
  draft_store_reviewed: '/marketing#store-network',
  store_published: '/marketing#store-network',
  store_activation_failed: '/marketing#store-network',
  performer_session_started: '/marketing#runtime',
  mission_started: '/marketing#runtime',
  mission_blocked: '/marketing#runtime',
  mission_completed: '/marketing#runtime',
  mission_failed: '/marketing#runtime',
  device_pair_requested: '/marketing#device-network',
  device_paired: '/marketing#device-network',
  device_online: '/marketing#device-network',
  device_offline: '/marketing#device-network',
  playlist_started: '/marketing#device-network',
  playlist_failed: '/marketing#device-network',
  heartbeat_missing: '/marketing#device-network',
  deployment_detected: '/app/console/control-tower',
  api_error_spike: '/app/console/control-tower',
  queue_backlog: '/app/console/control-tower',
  admin_qa_action: '/admin/discovery?view=qa',
  data_source_ingest_completed: '/connect',
};
