/**
 * System Insights Service
 * Creates and queries system insights generated by the watcher
 */

import { PrismaClient } from '@prisma/client';
import type {
  SystemWatcherInsight,
  SystemWatcherInsightSeverity,
} from '../../packages/ai-types/src/systemWatcher.js';

const prisma = new PrismaClient();

export interface CreateSystemInsightInput {
  title: string;
  severity: SystemWatcherInsightSeverity;
  category: string;
  summary: string;
  payload?: any;
}

/**
 * Create a system insight
 */
export async function createSystemInsight(
  input: CreateSystemInsightInput
): Promise<any> {
  const insight = await prisma.systemInsight.create({
    data: {
      title: input.title,
      severity: input.severity,
      category: input.category,
      summary: input.summary,
      payload: input.payload || {},
    },
  });

  return insight;
}

/**
 * Get recent insights
 */
export async function getRecentInsights(limit: number = 10): Promise<any[]> {
  const insights = await prisma.systemInsight.findMany({
    orderBy: {
      createdAt: 'desc',
    },
    take: limit,
  });

  return insights;
}

/**
 * Map database insight to SystemWatcherInsight format
 */
export function mapInsightToWatcherFormat(insight: any): SystemWatcherInsight {
  const payload = insight.payload || {};
  return {
    id: insight.id,
    title: insight.title,
    severity: insight.severity as SystemWatcherInsightSeverity,
    summary: insight.summary,
    category: insight.category as any,
    createdAt: insight.createdAt.toISOString(),
    context: payload.context,
    actions: payload.actions,
  };
}

