/**
 * System Insights Service
 * Creates and queries system insights generated by the watcher
 */

import { PrismaClient } from '@prisma/client';
import {
  buildInsightAction,
  inferEntryPointFromInsight,
  buildPayloadForEntryPoint,
  isInsightInputErrorLike,
} from '../utils/insightActionBuilder.js';

const prisma = new PrismaClient();

/**
 * Create a system insight
 * 
 * @param {Object} input - Insight input
 * @param {string} input.title - Insight title
 * @param {string} input.severity - 'info' | 'low' | 'medium' | 'high' | 'critical'
 * @param {string} input.category - Insight category
 * @param {string} input.summary - Insight summary
 * @param {any} [input.payload] - Additional payload
 * @returns {Promise<Object>} Created insight
 */
export async function createSystemInsight(input) {
  const insight = await prisma.systemInsight.create({
    data: {
      title: input.title,
      severity: input.severity,
      category: input.category,
      summary: input.summary,
      payload: input.payload || {},
    },
  });

  return insight;
}

/**
 * Get recent insights
 * 
 * @param {number} [limit=10] - Max number of insights
 * @returns {Promise<Array>} Array of insights
 */
export async function getRecentInsights(limit = 10) {
  const insights = await prisma.systemInsight.findMany({
    orderBy: {
      createdAt: 'desc',
    },
    take: limit,
  });

  return insights;
}

/**
 * Map database insight to SystemWatcherInsight format
 * 
 * @param {Object} insight - Database insight record
 * @returns {Object} Formatted insight with standardized action
 */
export function mapInsightToWatcherFormat(insight) {
  const payload = insight.payload || {};
  
  // Infer entry point from insight content
  const ctxDeviceId = payload.context?.deviceId ?? payload.deviceId;
  const entryPoint = inferEntryPointFromInsight(
    payload.tags || insight.category,
    insight.category,
    insight.title,
    insight.summary,
    { deviceId: ctxDeviceId },
  );

  // Build standardized action if entry point was inferred
  let action = null;
  if (entryPoint) {
    // Extract tenantId from context if available
    const tenantId = payload.tenantId || payload.context?.tenantId || '';
    if (tenantId) {
      try {
        const actionPayload = buildPayloadForEntryPoint(entryPoint, tenantId, {
          category: insight.category,
          ...payload.context,
        });

        action = buildInsightAction({
          description: `Take action: ${insight.title}`,
          entryPoint,
          payload: actionPayload,
          source: "insight_card",
          priority: insight.severity === "high" || insight.severity === "critical" ? "primary" : "secondary",
        });
      } catch (e) {
        if (isInsightInputErrorLike(e)) {
          console.warn(
            '[systemInsightsService] insight_action_skipped',
            JSON.stringify({ event: 'insight_action_skipped', code: e.code, entryPoint: e.entryPoint }),
          );
        } else {
          throw e;
        }
      }
    }
  }

  return {
    id: insight.id,
    title: insight.title,
    severity: insight.severity,
    summary: insight.summary,
    category: insight.category,
    createdAt: insight.createdAt.toISOString(),
    context: payload.context,
    actions: payload.actions, // Legacy actions format (keep for compatibility)
    action, // New standardized action
  };
}

