/**
 * Creative Agent Types
 * TypeScript interfaces for the Creative Agent (Imaginarium v1)
 */

/**
 * CreativeContext - Context for generating creative proposals
 */
export interface CreativeContext {
  /** Store/Business ID */
  storeId: string;
  /** User ID (optional) */
  userId?: string;
  /** Business type/category */
  businessType?: string;
  /** Country/location */
  country?: string;
  /** Scene type classification */
  sceneType: 'loyalty_card' | 'menu_photo' | 'shopfront' | 'campaign_setup' | 'generic';
  /** Extracted data (OCR results, detected objects, etc.) */
  extractedData: Record<string, unknown>;
  /** Current user intent */
  currentIntent?: string;
  /** Summary of what the Orchestrator is about to do / just did */
  currentPlanSummary?: string;
}

/**
 * CreativeProposal - A creative idea/proposal generated by the agent
 */
export interface CreativeProposal {
  /** Unique proposal ID */
  id: string;
  /** Proposal title */
  title: string;
  /** Proposal description */
  description: string;
  /** Proposal category */
  category: 'loyalty' | 'campaign' | 'branding' | 'cnet' | 'ar' | 'menu' | 'operational';
  /** Estimated impact level */
  estimatedImpact?: 'low' | 'medium' | 'high';
  /** Implementation complexity */
  complexity?: 'simple' | 'moderate' | 'advanced';
  /** Skill tags needed if proposal is accepted */
  requiredSkills?: string[];
  /** Short description of what will happen if proposal is accepted */
  followUpPlanSummary?: string;
}

/**
 * CreativeResponse - Response from Creative Agent
 */
export interface CreativeResponse {
  /** Array of creative proposals */
  proposals: CreativeProposal[];
}


