/** @type {Record<string, import('../industryBlueprintRegistry.js').IndustryBlueprint>} */
export const BEAUTY_BLUEPRINTS = {
  'beauty.hair_salon': {
    id: 'beauty.hair_salon',
    industry: 'beauty',
    label: 'Hair Salon',
    verticalSlugs: ['beauty.hair_salon', 'beauty.barber'],
    matchPatterns: [/\b(hair salon|haircut|hair cut|barber|balayage|colour|color|highlights)\b/i],
    templateKey: 'beauty_salon',
    categories: [
      { key: 'cuts', label: 'Haircuts' },
      { key: 'colour', label: 'Colour & Treatments' },
      { key: 'styling', label: 'Styling' },
      { key: 'extras', label: 'Extras' },
    ],
    imageQueryHints: {
      cuts: ['hair salon haircut', 'women haircut stylist', 'mens barber fade'],
      colour: ['balayage hair colour salon', 'hair highlights salon'],
      styling: ['blow dry hair salon', 'formal hair styling'],
      extras: ['hair treatment salon', 'keratin treatment hair'],
    },
    items: [
      { categoryKey: 'cuts', name: "Women's Haircut", description: 'Cut, wash, and blow-dry tailored to your style.', basePrice: 65, pricingModel: 'fixed', imageQueryHint: 'women haircut salon stylist' },
      { categoryKey: 'cuts', name: "Men's Haircut", description: 'Clipper and scissor cut with finish.', basePrice: 40, pricingModel: 'fixed', imageQueryHint: 'mens barber haircut fade' },
      { categoryKey: 'cuts', name: 'Children\'s Haircut', description: 'Gentle cut for kids under 12.', basePrice: 35, pricingModel: 'fixed' },
      { categoryKey: 'colour', name: 'Hair Colour', description: 'Full colour application with consultation.', basePrice: 120, pricingModel: 'from_price', fromPrice: 120, priceUnit: 'service' },
      { categoryKey: 'colour', name: 'Balayage', description: 'Hand-painted highlights for a natural sun-kissed look.', basePrice: 220, pricingModel: 'from_price', fromPrice: 220, priceUnit: 'service' },
      { categoryKey: 'colour', name: 'Highlights', description: 'Foils or cap highlights with toner finish.', basePrice: 160, pricingModel: 'from_price', fromPrice: 160, priceUnit: 'service' },
      { categoryKey: 'colour', name: 'Keratin Treatment', description: 'Smoothing treatment to reduce frizz for up to 3 months.', basePrice: 280, pricingModel: 'from_price', fromPrice: 280, priceUnit: 'service' },
      { categoryKey: 'styling', name: 'Blow Dry', description: 'Wash and professional blow-dry styling.', basePrice: 45, pricingModel: 'fixed' },
      { categoryKey: 'styling', name: 'Formal Upstyle', description: 'Event or wedding hair styling.', basePrice: 95, pricingModel: 'from_price', fromPrice: 95, priceUnit: 'service' },
      { categoryKey: 'extras', name: 'Eyebrow Wax', description: 'Shape and tidy brows with wax.', basePrice: 20, pricingModel: 'fixed' },
      { categoryKey: 'extras', name: 'Deep Conditioning Treatment', description: 'Intensive moisture and repair treatment.', basePrice: 35, pricingModel: 'fixed' },
    ],
    promptHints: 'Generate a hair salon menu: cuts, colour, balayage, treatments. Fixed salon pricing — no retail variants.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Expert stylists', description: 'Cuts, colour, and treatments tailored to you.' },
        { icon: '⚡', label: 'Easy booking', description: 'Reserve your appointment online in minutes.' },
        { icon: '♥', label: 'Salon experience', description: 'Relax with professional care and great results.' },
      ],
      heroImageKeywords: ['hair salon interior stylist', 'professional haircut salon'],
      ctaLabel: 'Book appointment',
    },
  },
  'beauty.nails': {
    id: 'beauty.nails',
    industry: 'beauty',
    label: 'Nail Salon',
    verticalSlugs: ['beauty.nails'],
    // Must NOT share beauty_salon — that template expands haircut items.
    matchPatterns: [/\b(nails?|nail salon|manicure|pedicure|nail art|gel nails|acrylic nails|sns|dip powder)\b/i],
    templateKey: 'beauty_nails',
    categories: [
      { key: 'manicure', label: 'Manicure' },
      { key: 'pedicure', label: 'Pedicure' },
      { key: 'extensions', label: 'Extensions' },
      { key: 'extras', label: 'Extras' },
    ],
    items: [
      { categoryKey: 'manicure', name: 'Classic Manicure', description: 'File, shape, cuticle care and polish.', basePrice: 30, pricingModel: 'fixed' },
      { categoryKey: 'manicure', name: 'Gel Manicure', description: 'Long-lasting gel polish with cuticle care.', basePrice: 45, pricingModel: 'fixed' },
      { categoryKey: 'pedicure', name: 'Classic Pedicure', description: 'Foot soak, exfoliation, cuticle care and polish.', basePrice: 45, pricingModel: 'fixed' },
      { categoryKey: 'pedicure', name: 'Spa Pedicure', description: 'Deluxe pedicure with scrub and massage.', basePrice: 60, pricingModel: 'fixed' },
      { categoryKey: 'extensions', name: 'Acrylic Full Set', description: 'Acrylic extensions with your choice of shape.', basePrice: 80, pricingModel: 'fixed' },
      { categoryKey: 'extensions', name: 'Acrylic Infill', description: 'Maintenance infill for acrylic extensions.', basePrice: 60, pricingModel: 'fixed' },
      { categoryKey: 'extras', name: 'Nail Art (per nail)', description: 'Custom design per nail.', basePrice: 5, pricingModel: 'fixed' },
      { categoryKey: 'extras', name: 'Gel Removal', description: 'Safe removal of gel polish.', basePrice: 15, pricingModel: 'fixed' },
    ],
    promptHints: 'Generate nail salon services with fixed appointment pricing.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Beautiful nails', description: 'Manicures, pedicures, and nail art.' },
        { icon: '⚡', label: 'Walk-ins welcome', description: 'Book ahead or drop in when available.' },
        { icon: '♥', label: 'Hygiene focused', description: 'Sanitised tools and premium products.' },
      ],
      heroImageKeywords: ['nail salon manicure', 'gel nails salon'],
      ctaLabel: 'Book appointment',
    },
  },
  'beauty.spa': {
    id: 'beauty.spa',
    industry: 'beauty',
    label: 'Spa & Beauty',
    verticalSlugs: ['beauty.spa', 'beauty.lashes_brows', 'beauty.waxing'],
    matchPatterns: [/\b(spa|facial|massage|wax|lash|brow|eyelash|skincare)\b/i],
    // Must NOT share beauty_salon — that template expands haircut items.
    templateKey: 'beauty_spa',
    categories: [
      { key: 'facials', label: 'Facials & Skin' },
      { key: 'massage', label: 'Massage' },
      { key: 'lashes', label: 'Lashes & Brows' },
      { key: 'waxing', label: 'Waxing' },
    ],
    items: [
      { categoryKey: 'facials', name: 'Classic Facial', description: 'Cleanse, exfoliate, mask, and moisturise.', basePrice: 85, pricingModel: 'fixed' },
      { categoryKey: 'facials', name: 'Hydrating Facial', description: 'Deep hydration for dry or dull skin.', basePrice: 95, pricingModel: 'fixed' },
      { categoryKey: 'massage', name: 'Relaxation Massage (60 min)', description: 'Full-body relaxation massage.', basePrice: 95, pricingModel: 'fixed', durationMinutes: 60 },
      { categoryKey: 'massage', name: 'Remedial Massage (60 min)', description: 'Targeted muscle and tension relief.', basePrice: 110, pricingModel: 'fixed', durationMinutes: 60 },
      { categoryKey: 'lashes', name: 'Eyelash Extensions', description: 'Classic or volume lash extensions.', basePrice: 120, pricingModel: 'from_price', fromPrice: 120, priceUnit: 'set' },
      { categoryKey: 'lashes', name: 'Lash Lift & Tint', description: 'Lift and tint for naturally fuller lashes.', basePrice: 85, pricingModel: 'fixed' },
      { categoryKey: 'lashes', name: 'Eyebrow Lamination', description: 'Fluffy, brushed-up brow finish.', basePrice: 65, pricingModel: 'fixed' },
      { categoryKey: 'waxing', name: 'Brazilian Wax', description: 'Professional intimate waxing.', basePrice: 55, pricingModel: 'fixed' },
      { categoryKey: 'waxing', name: 'Leg Wax (Full)', description: 'Full leg wax from ankle to upper thigh.', basePrice: 45, pricingModel: 'fixed' },
      { categoryKey: 'waxing', name: 'Underarm Wax', description: 'Quick and effective underarm wax.', basePrice: 20, pricingModel: 'fixed' },
    ],
    promptHints: 'Generate spa and beauty treatment menu with fixed session pricing.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Relax & restore', description: 'Facials, massage, and beauty treatments.' },
        { icon: '⚡', label: 'Skilled therapists', description: 'Experienced team in a calm environment.' },
        { icon: '♥', label: 'Self-care', description: 'Treat yourself with premium products and care.' },
      ],
      heroImageKeywords: ['spa facial treatment room', 'relaxation massage spa'],
      ctaLabel: 'Book treatment',
    },
  },
};
