/** @type {Record<string, import('../industryBlueprintRegistry.js').IndustryBlueprint>} */
export const FOOD_BLUEPRINTS = {
  'food.restaurant': {
    id: 'food.restaurant',
    industry: 'food',
    label: 'Restaurant',
    verticalSlugs: ['food.restaurant', 'food'],
    matchPatterns: [/\b(restaurant|dining|bistro|grill|eatery|kitchen|chef)\b/i],
    templateKey: 'food_restaurant_generic',
    categories: [
      { key: 'entrees', label: 'Entrees' },
      { key: 'mains', label: 'Main Meals' },
      { key: 'family', label: 'Family Meals' },
      { key: 'desserts', label: 'Desserts' },
      { key: 'drinks', label: 'Drinks' },
    ],
    imageQueryHints: {
      entrees: ['restaurant starter plated', 'appetizer sharing plate'],
      mains: ['restaurant main course plated', 'grilled dish restaurant'],
      family: ['family meal sharing platter restaurant', 'combo meal restaurant'],
      desserts: ['restaurant dessert plated', 'cheesecake slice'],
      drinks: ['restaurant drinks table', 'soft drink glass'],
    },
    items: [
      { categoryKey: 'entrees', name: 'Spring Rolls', description: 'Crispy vegetable spring rolls with dipping sauce.', price: '$12.00', imageQueryHint: 'crispy spring rolls appetizer' },
      { categoryKey: 'entrees', name: 'Garlic Bread', description: 'Toasted garlic bread with herb butter.', price: '$9.00' },
      { categoryKey: 'entrees', name: 'Soup of the Day', description: "Chef's daily soup served with bread.", price: '$11.00' },
      { categoryKey: 'entrees', name: 'Seasonal Salad', description: 'Fresh greens with house dressing.', price: '$14.00' },
      { categoryKey: 'mains', name: "Chef's Recommendation", description: 'Ask your server for tonight\'s chef special.', price: '$32.00', tags: ['popular'] },
      { categoryKey: 'mains', name: 'Grilled Chicken', description: 'Herb-marinated chicken with seasonal vegetables.', price: '$28.00' },
      { categoryKey: 'mains', name: 'Beef Stir Fry', description: 'Wok-tossed beef with Asian greens and rice.', price: '$29.00' },
      { categoryKey: 'mains', name: 'Grilled Salmon', description: 'Atlantic salmon with lemon butter and mash.', price: '$34.00' },
      { categoryKey: 'mains', name: 'Vegetarian Pasta', description: 'Seasonal vegetables in tomato basil sauce.', price: '$24.00', tags: ['vegetarian'] },
      { categoryKey: 'mains', name: 'Seafood Laksa', description: 'Spiced coconut broth with prawns and noodles.', price: '$26.00', tags: ['popular'] },
      { categoryKey: 'family', name: 'Family Meal Deal', description: 'Two mains, two sides, and dessert to share.', price: '$65.00' },
      { categoryKey: 'family', name: 'Kids Meal', description: 'Chicken tenders, chips, and a drink.', price: '$14.00' },
      { categoryKey: 'family', name: 'Lunch Combo', description: 'Main and drink — available weekdays 12–3pm.', price: '$22.00' },
      { categoryKey: 'desserts', name: 'Chocolate Cake', description: 'Rich layer cake with chocolate ganache.', price: '$12.00' },
      { categoryKey: 'desserts', name: 'Cheesecake', description: 'Classic baked cheesecake with berry compote.', price: '$12.00' },
      { categoryKey: 'desserts', name: 'Ice Cream Sundae', description: 'Vanilla ice cream with toppings.', price: '$10.00' },
      { categoryKey: 'drinks', name: 'Soft Drink', description: 'Choice of flavours.', price: '$4.50' },
      { categoryKey: 'drinks', name: 'Fresh Juice', description: 'Orange, apple, or seasonal blend.', price: '$6.00' },
      { categoryKey: 'drinks', name: 'Sparkling Water', description: 'Chilled sparkling mineral water.', price: '$5.00' },
    ],
    promptHints: 'Generate a realistic restaurant menu with entrees, mains, desserts, and drinks. Use real dish names — never service packages or retail placeholders.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Fresh ingredients', description: 'Seasonal menus crafted by our kitchen team.' },
        { icon: '⚡', label: 'Book a table', description: 'Dine in or order takeaway online.' },
        { icon: '♥', label: 'Something for everyone', description: 'Family meals, kids options, and chef specials.' },
      ],
      heroImageKeywords: ['restaurant dining room interior', 'plated restaurant dish'],
      ctaLabel: 'View menu',
    },
  },
  'food.bakery': {
    id: 'food.bakery',
    industry: 'food',
    label: 'Bakery',
    verticalSlugs: ['food.bakery'],
    matchPatterns: [/\b(bakery|baker|bread|pastry|patisserie|sourdough|croissant)\b/i],
    templateKey: 'food_bakery',
    categories: [
      { key: 'bread', label: 'Bread & Loaves' },
      { key: 'pastries', label: 'Pastries' },
      { key: 'cakes', label: 'Cakes & Sweets' },
      { key: 'drinks', label: 'Drinks' },
    ],
    imageQueryHints: {
      bread: ['artisan sourdough loaf bakery', 'fresh baguette bakery'],
      pastries: ['croissant bakery display', 'vanilla slice pastry'],
      cakes: ['chocolate cake bakery', 'birthday cake display'],
      drinks: ['coffee cup bakery', 'hot chocolate cafe'],
    },
    items: [
      { categoryKey: 'bread', name: 'Sourdough', description: 'Naturally leavened sourdough, baked daily.', price: '$9.50', imageQueryHint: 'sourdough loaf bakery' },
      { categoryKey: 'bread', name: 'Baguette', description: 'Classic French baguette with crisp crust.', price: '$4.50' },
      { categoryKey: 'bread', name: 'Focaccia', description: 'Olive oil focaccia with sea salt.', price: '$7.00' },
      { categoryKey: 'pastries', name: 'Croissant', description: 'Buttery, flaky all-butter croissant.', price: '$5.50', imageQueryHint: 'fresh croissant bakery' },
      { categoryKey: 'pastries', name: 'Pain au Chocolat', description: 'Chocolate-filled pastry.', price: '$6.00' },
      { categoryKey: 'pastries', name: 'Vanilla Slice', description: 'Custard slice with passionfruit icing.', price: '$6.50' },
      { categoryKey: 'cakes', name: 'Cheesecake', description: 'Baked cheesecake by the slice.', price: '$7.50' },
      { categoryKey: 'cakes', name: 'Chocolate Cake', description: 'Rich chocolate layer cake slice.', price: '$7.50' },
      { categoryKey: 'cakes', name: 'Birthday Cake', description: 'Custom birthday cakes — order 48 hours ahead.', price: '$65.00' },
      { categoryKey: 'drinks', name: 'Coffee', description: 'Espresso-based coffee drinks.', price: '$4.50' },
      { categoryKey: 'drinks', name: 'Hot Chocolate', description: 'Real chocolate hot drink.', price: '$5.00' },
    ],
    promptHints: 'Generate a bakery menu: bread, pastries, cakes, drinks. Real baked goods names only.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Baked fresh daily', description: 'Bread, pastries, and cakes from our ovens each morning.' },
        { icon: '⚡', label: 'Order ahead', description: 'Pre-order cakes and catering platters.' },
        { icon: '♥', label: 'Artisan quality', description: 'Traditional recipes and quality ingredients.' },
      ],
      heroImageKeywords: ['bakery display pastries bread', 'artisan bakery interior'],
      ctaLabel: 'Order now',
    },
  },
  'food.cafe': {
    id: 'food.cafe',
    industry: 'food',
    label: 'Café',
    verticalSlugs: ['food.cafe'],
    matchPatterns: [/\b(cafe|café|coffee|espresso|barista)\b/i],
    templateKey: 'cafe',
    categories: [
      { key: 'coffee', label: 'Coffee' },
      { key: 'other_drinks', label: 'Other Drinks' },
      { key: 'food', label: 'Food' },
      { key: 'bakery', label: 'Bakery' },
    ],
    imageQueryHints: {
      coffee: ['latte art cafe', 'espresso coffee cup'],
      other_drinks: ['iced coffee glass', 'hot chocolate cafe'],
      food: ['cafe sandwich toast', 'chicken sandwich cafe'],
      bakery: ['blueberry muffin cafe', 'banana bread slice'],
    },
    items: [
      { categoryKey: 'coffee', name: 'Flat White', description: 'Double ristretto with velvety microfoam.', price: '$4.50', imageQueryHint: 'flat white latte art' },
      { categoryKey: 'coffee', name: 'Latte', description: 'Espresso with steamed milk.', price: '$4.50' },
      { categoryKey: 'coffee', name: 'Cappuccino', description: 'Espresso with foam and a dusting of chocolate.', price: '$4.50' },
      { categoryKey: 'coffee', name: 'Mocha', description: 'Espresso, chocolate, and steamed milk.', price: '$5.00' },
      { categoryKey: 'coffee', name: 'Long Black', description: 'Double espresso with hot water.', price: '$4.00' },
      { categoryKey: 'other_drinks', name: 'Iced Coffee', description: 'Chilled espresso with milk and ice.', price: '$5.50' },
      { categoryKey: 'other_drinks', name: 'Hot Chocolate', description: 'Rich drinking chocolate.', price: '$4.50' },
      { categoryKey: 'food', name: 'Chicken Sandwich', description: 'Grilled chicken, salad, and aioli on sourdough.', price: '$14.00' },
      { categoryKey: 'food', name: 'Ham & Cheese Toastie', description: 'Toasted sourdough with leg ham and cheddar.', price: '$12.00' },
      { categoryKey: 'food', name: 'Avocado Toast', description: 'Smashed avo, feta, and cherry tomatoes.', price: '$16.00' },
      { categoryKey: 'bakery', name: 'Blueberry Muffin', description: 'Freshly baked blueberry muffin.', price: '$4.50' },
      { categoryKey: 'bakery', name: 'Banana Bread', description: 'Moist banana bread slice.', price: '$4.50' },
      { categoryKey: 'bakery', name: 'Croissant', description: 'All-butter croissant.', price: '$5.00' },
    ],
    promptHints: 'Generate a café menu: espresso drinks, light meals, toasties, and baked goods.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Great coffee', description: 'Single-origin beans and skilled baristas.' },
        { icon: '⚡', label: 'All-day dining', description: 'Breakfast, lunch, and sweet treats.' },
        { icon: '♥', label: 'Local favourite', description: 'A welcoming spot to meet, work, and relax.' },
      ],
      heroImageKeywords: ['cafe interior coffee shop', 'barista making latte'],
      ctaLabel: 'Order coffee',
    },
  },
};
