/** @type {Record<string, import('../industryBlueprintRegistry.js').IndustryBlueprint>} */
export const PROFESSIONAL_BLUEPRINTS = {
  // Finance/capital first so name matches win over accounting when both could apply.
  'services.finance': {
    id: 'services.finance',
    industry: 'professional',
    label: 'Capital & Investment Advisory',
    verticalSlugs: ['services.finance'],
    matchPatterns: [
      /\b(capital group|capital partners|capital management|private equity|venture capital|asset management|wealth management|investment advice|investment advisory|fund manager)\b/i,
      /\b(capital|investment|investments|wealth|private equity|venture)\b/i,
      /\b(finance|financial|financial advisor|financial advisory)\b/i,
    ],
    templateKey: 'professional_services',
    categories: [
      { key: 'advisory', label: 'Investment Advisory' },
      { key: 'capital', label: 'Capital Solutions' },
      { key: 'planning', label: 'Planning' },
      { key: 'consult', label: 'Consultations' },
    ],
    items: [
      {
        categoryKey: 'consult',
        name: 'Initial Investment Consultation',
        description: 'Discovery call to understand goals, risk appetite, and capital priorities.',
        serviceMode: 'fixed_booking',
        pricingModel: 'fixed',
        basePrice: 0,
        durationMinutes: 30,
        imageQueryHint: 'investment advisor client meeting modern office',
      },
      {
        categoryKey: 'advisory',
        name: 'Portfolio Review',
        description: 'Review of holdings and allocation with written recommendations.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 350,
        priceUnit: 'session',
        durationMinutes: 60,
        imageQueryHint: 'financial portfolio review laptop charts office',
      },
      {
        categoryKey: 'advisory',
        name: 'Investment Strategy Session',
        description: '1-hour strategy session focused on growth, diversification, and timing.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 450,
        priceUnit: 'hour',
        durationMinutes: 60,
        imageQueryHint: 'corporate finance strategy meeting boardroom',
      },
      {
        categoryKey: 'capital',
        name: 'Capital Raising Advisory',
        description: 'Guidance on preparing for capital raises and investor conversations.',
        serviceMode: 'quote_required',
        pricingModel: 'from_price',
        fromPrice: 1500,
        priceUnit: 'engagement',
        imageQueryHint: 'startup investor pitch meeting professional',
      },
      {
        categoryKey: 'capital',
        name: 'Deal Structuring Support',
        description: 'Support evaluating structure, terms, and next steps for a transaction.',
        serviceMode: 'quote_required',
        pricingModel: 'from_price',
        fromPrice: 2000,
        priceUnit: 'engagement',
        imageQueryHint: 'business acquisition handshake corporate office',
      },
      {
        categoryKey: 'planning',
        name: 'Wealth Planning Review',
        description: 'Holistic review of goals, liquidity, and long-term capital plans.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 500,
        priceUnit: 'session',
        durationMinutes: 90,
        imageQueryHint: 'wealth planning advisor modern office skyline',
      },
      {
        categoryKey: 'consult',
        name: 'Follow-up Advisory Call',
        description: 'Short follow-up to refine recommendations after the initial consultation.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 150,
        priceUnit: 'call',
        durationMinutes: 30,
        imageQueryHint: 'video call financial advisor professional',
      },
    ],
    imageQueryHints: {
      advisory: ['investment advisory meeting', 'portfolio review office'],
      capital: ['capital raising investor meeting', 'corporate finance office'],
      planning: ['wealth planning consultation', 'financial planning desk'],
      consult: ['professional consultation modern office'],
    },
    promptHints:
      'Generate capital, investment, and wealth advisory services. Do NOT invent tax returns, BAS, bookkeeping, or payroll offerings.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Capital focused', description: 'Investment advice and capital strategy — not tax prep.' },
        { icon: '⚡', label: 'Clear next steps', description: 'Practical guidance for decisions that matter.' },
        { icon: '♥', label: 'Client first', description: 'Transparent conversations about risk and opportunity.' },
      ],
      heroImageKeywords: [
        'corporate finance skyline modern office',
        'investment advisor meeting boardroom',
        'financial district glass buildings',
      ],
      ctaLabel: 'Book consultation',
    },
  },
  'services.accounting': {
    id: 'services.accounting',
    industry: 'professional',
    label: 'Accounting',
    verticalSlugs: ['services.accounting'],
    // Accounting / tax / bookkeeping only — capital/investment firms must use services.finance.
    matchPatterns: [
      /\b(accountant|accounting|bookkeep|bookkeeper|tax return|tax agent|bas|payroll|stp reporting)\b/i,
    ],
    templateKey: 'professional_services',
    categories: [
      { key: 'tax', label: 'Tax & Compliance' },
      { key: 'business', label: 'Business Services' },
      { key: 'advisory', label: 'Advisory' },
      { key: 'consult', label: 'Consultations' },
    ],
    items: [
      {
        categoryKey: 'tax',
        name: 'Individual Tax Return',
        description: 'Prepare and lodge personal tax return.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 180,
        priceUnit: 'return',
        imageQueryHint: 'tax accountant desk documents office',
      },
      {
        categoryKey: 'tax',
        name: 'Business Tax Return',
        description: 'Company, trust, or partnership tax return.',
        serviceMode: 'quote_required',
        pricingModel: 'from_price',
        fromPrice: 450,
        priceUnit: 'return',
        imageQueryHint: 'business tax preparation office paperwork',
      },
      {
        categoryKey: 'tax',
        name: 'BAS Lodgement',
        description: 'Prepare and lodge business activity statements.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 120,
        priceUnit: 'quarter',
        imageQueryHint: 'accountant BAS lodgement laptop office',
      },
      {
        categoryKey: 'business',
        name: 'Bookkeeping (Monthly)',
        description: 'Reconcile accounts and prepare monthly reports.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 350,
        priceUnit: 'month',
        imageQueryHint: 'bookkeeping spreadsheet professional office',
      },
      {
        categoryKey: 'business',
        name: 'Payroll Processing',
        description: 'Weekly or fortnightly payroll with STP reporting.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 80,
        priceUnit: 'run',
        imageQueryHint: 'payroll processing office computer',
      },
      {
        categoryKey: 'advisory',
        name: 'Business Advisory Session',
        description: '1-hour strategy session with a qualified advisor.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 250,
        priceUnit: 'hour',
        durationMinutes: 60,
        imageQueryHint: 'business advisor meeting professional office',
      },
      {
        categoryKey: 'consult',
        name: 'Initial Consultation',
        description: 'Free 30-minute discovery call for new clients.',
        serviceMode: 'fixed_booking',
        pricingModel: 'fixed',
        basePrice: 0,
        durationMinutes: 30,
        imageQueryHint: 'accountant client consultation office',
      },
    ],
    promptHints: 'Generate accounting and bookkeeping services with fixed and from-price professional fees.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Trusted advisors', description: 'Tax, bookkeeping, and business compliance.' },
        { icon: '⚡', label: 'Deadline ready', description: 'BAS, payroll, and tax returns handled on time.' },
        { icon: '♥', label: 'Clear advice', description: 'Plain-language guidance for your finances.' },
      ],
      heroImageKeywords: ['accounting office professional', 'tax accountant meeting'],
      ctaLabel: 'Book consultation',
    },
  },
  'services.legal': {
    id: 'services.legal',
    industry: 'professional',
    label: 'Legal Services',
    verticalSlugs: ['services.legal'],
    matchPatterns: [/\b(lawyer|legal|solicitor|conveyanc|litigation|family law|will|estate)\b/i],
    templateKey: 'professional_services',
    categories: [
      { key: 'property', label: 'Property & Conveyancing' },
      { key: 'family', label: 'Family Law' },
      { key: 'business', label: 'Business Law' },
      { key: 'consult', label: 'Consultations' },
    ],
    items: [
      {
        categoryKey: 'property',
        name: 'Conveyancing — Purchase',
        description: 'Legal review and settlement for property purchase.',
        serviceMode: 'quote_required',
        pricingModel: 'from_price',
        fromPrice: 1200,
        priceUnit: 'matter',
        imageQueryHint: 'conveyancing lawyer property documents',
      },
      {
        categoryKey: 'property',
        name: 'Conveyancing — Sale',
        description: 'Contract preparation and settlement for property sale.',
        serviceMode: 'quote_required',
        pricingModel: 'from_price',
        fromPrice: 900,
        priceUnit: 'matter',
        imageQueryHint: 'property sale legal documents office',
      },
      {
        categoryKey: 'family',
        name: 'Family Law Consultation',
        description: 'Initial advice on separation, parenting, or property.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 350,
        priceUnit: 'hour',
        durationMinutes: 60,
        imageQueryHint: 'family law consultation professional office',
      },
      {
        categoryKey: 'family',
        name: 'Consent Orders',
        description: 'Draft and lodge consent orders for parenting/property.',
        serviceMode: 'quote_required',
        pricingModel: 'from_price',
        fromPrice: 2500,
        priceUnit: 'matter',
        imageQueryHint: 'legal documents signing office',
      },
      {
        categoryKey: 'business',
        name: 'Contract Review',
        description: 'Review commercial contracts with written advice.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 450,
        priceUnit: 'contract',
        imageQueryHint: 'contract review lawyer desk',
      },
      {
        categoryKey: 'business',
        name: 'Business Formation',
        description: 'Set up company or trust structure with documents.',
        serviceMode: 'quote_required',
        pricingModel: 'from_price',
        fromPrice: 1500,
        priceUnit: 'matter',
        imageQueryHint: 'business formation lawyer meeting',
      },
      {
        categoryKey: 'consult',
        name: 'Initial Legal Consultation',
        description: '30-minute consultation to assess your matter.',
        serviceMode: 'fixed_booking',
        pricingModel: 'from_price',
        fromPrice: 180,
        priceUnit: 'consult',
        durationMinutes: 30,
        imageQueryHint: 'lawyer client consultation office',
      },
    ],
    promptHints: 'Generate legal services with matter-based and hourly professional pricing.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Experienced lawyers', description: 'Property, family, and business law expertise.' },
        { icon: '⚡', label: 'Clear process', description: 'Step-by-step guidance through your matter.' },
        { icon: '♥', label: 'Client focused', description: 'Practical advice with transparent fee estimates.' },
      ],
      heroImageKeywords: ['law office professional meeting', 'legal consultation'],
      ctaLabel: 'Book consultation',
    },
  },
};
