/** @type {Record<string, import('../industryBlueprintRegistry.js').IndustryBlueprint>} */
export const RETAIL_BLUEPRINTS = {
  'retail.flower': {
    id: 'retail.flower',
    industry: 'florist',
    label: 'Florist',
    verticalSlugs: ['retail.flower'],
    matchPatterns: [/\b(florist|flower|flowers|floral|bouquet|bloom|blooms)\b/i],
    templateKey: 'florist',
    categories: [
      { key: 'bouquets', label: 'Bouquets' },
      { key: 'arrangements', label: 'Arrangements' },
      { key: 'occasions', label: 'Occasions' },
      { key: 'plants', label: 'Plants & Gifts' },
    ],
    imageQueryHints: {
      bouquets: ['flower bouquet roses', 'florist wrapped bouquet'],
      arrangements: ['floral arrangement vase', 'table centrepiece flowers'],
      occasions: ['wedding bouquet flowers', 'sympathy flower arrangement'],
      plants: ['potted plant gift', 'succulent arrangement'],
    },
    items: [
      { categoryKey: 'bouquets', name: 'Classic Rose Bouquet', description: 'A dozen premium roses wrapped and ribboned.', price: '$85.00', basePrice: 85, imageQueryHint: 'red rose bouquet florist' },
      { categoryKey: 'bouquets', name: 'Seasonal Mixed Bouquet', description: 'Fresh seasonal blooms hand-tied.', price: '$65.00', basePrice: 65 },
      { categoryKey: 'bouquets', name: 'Native Australian Bouquet', description: 'Proteas, banksias, and native foliage.', price: '$75.00', basePrice: 75 },
      { categoryKey: 'arrangements', name: 'Table Arrangement', description: 'Vase arrangement for dining or reception.', price: '$95.00', basePrice: 95 },
      { categoryKey: 'arrangements', name: 'Corporate Arrangement', description: 'Long-lasting arrangement for offices.', price: '$110.00', basePrice: 110 },
      { categoryKey: 'occasions', name: 'Wedding Bouquet', description: 'Custom bridal bouquet — consultation included.', price: '$180.00', basePrice: 180 },
      { categoryKey: 'occasions', name: 'Sympathy Wreath', description: 'Traditional wreath for funeral services.', price: '$150.00', basePrice: 150 },
      { categoryKey: 'occasions', name: 'Birthday Box', description: 'Bright boxed arrangement with card.', price: '$70.00', basePrice: 70 },
      { categoryKey: 'plants', name: 'Orchid Plant', description: 'Elegant potted orchid in ceramic pot.', price: '$55.00', basePrice: 55 },
      { categoryKey: 'plants', name: 'Succulent Gift Box', description: 'Assorted succulents in a gift box.', price: '$45.00', basePrice: 45 },
    ],
    promptHints: 'Generate florist products: bouquets, arrangements, occasion flowers, plants. Real flower names — no generic retail placeholders.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Fresh daily', description: 'Quality blooms sourced and arranged in store.' },
        { icon: '⚡', label: 'Same-day delivery', description: 'Order before midday for local delivery.' },
        { icon: '♥', label: 'Custom designs', description: 'Weddings, events, and personal arrangements.' },
      ],
      heroImageKeywords: ['flower shop interior', 'florist bouquet display'],
      ctaLabel: 'Order flowers',
    },
  },
  'retail.furniture': {
    id: 'retail.furniture',
    industry: 'furniture',
    label: 'Furniture Store',
    verticalSlugs: ['retail.furniture'],
    matchPatterns: [/\b(furniture|sofa|couch|bed|mattress|dining table|wardrobe|homeware)\b/i],
    templateKey: 'retail_furniture',
    categories: [
      { key: 'living', label: 'Living Room' },
      { key: 'bedroom', label: 'Bedroom' },
      { key: 'dining', label: 'Dining' },
      { key: 'office', label: 'Home Office' },
    ],
    items: [
      { categoryKey: 'living', name: '3-Seater Sofa', description: 'Comfortable fabric sofa with timber legs.', price: '$1,299.00', basePrice: 1299 },
      { categoryKey: 'living', name: 'Coffee Table', description: 'Solid oak coffee table with storage shelf.', price: '$449.00', basePrice: 449 },
      { categoryKey: 'living', name: 'Entertainment Unit', description: 'TV unit with cable management and drawers.', price: '$599.00', basePrice: 599 },
      { categoryKey: 'bedroom', name: 'Queen Bed Frame', description: 'Upholstered queen bed frame with slats.', price: '$899.00', basePrice: 899 },
      { categoryKey: 'bedroom', name: 'Bedside Table', description: 'Two-drawer bedside with soft-close runners.', price: '$199.00', basePrice: 199 },
      { categoryKey: 'bedroom', name: 'Wardrobe', description: '2-door wardrobe with hanging and shelving.', price: '$749.00', basePrice: 749 },
      { categoryKey: 'dining', name: 'Dining Table (6-seater)', description: 'Timber dining table seats six comfortably.', price: '$1,099.00', basePrice: 1099 },
      { categoryKey: 'dining', name: 'Dining Chairs (Set of 4)', description: 'Upholstered dining chairs with timber legs.', price: '$599.00', basePrice: 599 },
      { categoryKey: 'office', name: 'Desk', description: 'Home office desk with drawer storage.', price: '$399.00', basePrice: 399 },
      { categoryKey: 'office', name: 'Office Chair', description: 'Ergonomic chair with lumbar support.', price: '$349.00', basePrice: 349 },
    ],
    promptHints: 'Generate real furniture product names with specifications and price ranges.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Quality furniture', description: 'Living, bedroom, and dining pieces for every home.' },
        { icon: '⚡', label: 'Delivery available', description: 'Local delivery and assembly options.' },
        { icon: '♥', label: 'Showroom ready', description: 'See finishes and fabrics before you buy.' },
      ],
      heroImageKeywords: ['furniture showroom living room', 'modern furniture store interior'],
      ctaLabel: 'Browse collection',
    },
  },
  'retail.electronics': {
    id: 'retail.electronics',
    industry: 'electronics',
    label: 'Electronics',
    verticalSlugs: ['retail.electronics'],
    templateKey: 'retail_electronics',
    categories: [
      { key: 'phones', label: 'Phones & Tablets' },
      { key: 'computers', label: 'Computers' },
      { key: 'audio', label: 'Audio' },
      { key: 'accessories', label: 'Accessories' },
    ],
    items: [
      { categoryKey: 'phones', name: 'Smartphone', description: 'Latest generation smartphone with warranty.', price: '$999.00', basePrice: 999 },
      { categoryKey: 'phones', name: 'Tablet', description: '10-inch tablet for work and entertainment.', price: '$649.00', basePrice: 649 },
      { categoryKey: 'computers', name: 'Laptop', description: 'Lightweight laptop for everyday productivity.', price: '$1,299.00', basePrice: 1299 },
      { categoryKey: 'computers', name: 'Wireless Mouse', description: 'Ergonomic wireless mouse with long battery life.', price: '$49.00', basePrice: 49 },
      { categoryKey: 'audio', name: 'Wireless Earbuds', description: 'Noise-cancelling earbuds with charging case.', price: '$199.00', basePrice: 199 },
      { categoryKey: 'audio', name: 'Bluetooth Speaker', description: 'Portable waterproof speaker.', price: '$89.00', basePrice: 89 },
      { categoryKey: 'accessories', name: 'Phone Case', description: 'Protective case with raised edges.', price: '$29.00', basePrice: 29 },
      { categoryKey: 'accessories', name: 'USB-C Charger', description: 'Fast charger with USB-C cable included.', price: '$39.00', basePrice: 39 },
    ],
    promptHints: 'Generate electronics products with real categories and price ranges.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Latest tech', description: 'Phones, laptops, audio, and accessories.' },
        { icon: '⚡', label: 'Expert advice', description: 'Help choosing the right device for your needs.' },
        { icon: '♥', label: 'Warranty support', description: 'Genuine products with local warranty.' },
      ],
      heroImageKeywords: ['electronics store display', 'technology retail shop'],
      ctaLabel: 'Shop tech',
    },
  },
  'retail.grocery': {
    id: 'retail.grocery',
    industry: 'grocery',
    label: 'Grocery',
    verticalSlugs: ['retail.grocery'],
    templateKey: 'retail_grocery',
    categories: [
      { key: 'produce', label: 'Fresh Produce' },
      { key: 'dairy', label: 'Dairy & Eggs' },
      { key: 'pantry', label: 'Pantry' },
      { key: 'bakery', label: 'In-store Bakery' },
    ],
    items: [
      { categoryKey: 'produce', name: 'Seasonal Fruit Box', description: 'Mixed seasonal fruit — contents vary weekly.', price: '$18.00', basePrice: 18 },
      { categoryKey: 'produce', name: 'Vegetable Pack', description: 'Fresh mixed vegetables for the week.', price: '$15.00', basePrice: 15 },
      { categoryKey: 'dairy', name: 'Free Range Eggs (dozen)', description: 'Local free-range eggs.', price: '$7.50', basePrice: 7.5 },
      { categoryKey: 'dairy', name: 'Artisan Cheese Selection', description: 'Three local cheeses with tasting notes.', price: '$22.00', basePrice: 22 },
      { categoryKey: 'pantry', name: 'Extra Virgin Olive Oil', description: 'Cold-pressed olive oil 750ml.', price: '$16.00', basePrice: 16 },
      { categoryKey: 'pantry', name: 'Pasta & Sauce Bundle', description: 'Artisan pasta with house-made sauce.', price: '$14.00', basePrice: 14 },
      { categoryKey: 'bakery', name: 'Sourdough Loaf', description: 'Baked fresh in store each morning.', price: '$8.50', basePrice: 8.5 },
      { categoryKey: 'bakery', name: 'Croissant (4 pack)', description: 'Butter croissants baked daily.', price: '$12.00', basePrice: 12 },
    ],
    promptHints: 'Generate grocery products with real food item names and prices.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Fresh daily', description: 'Produce, dairy, and pantry staples.' },
        { icon: '⚡', label: 'Local suppliers', description: 'Supporting local growers and makers.' },
        { icon: '♥', label: 'Neighbourhood store', description: 'Friendly service and quality ingredients.' },
      ],
      heroImageKeywords: ['grocery store fresh produce', 'local market vegetables'],
      ctaLabel: 'Shop groceries',
    },
  },
};
