/** @typedef {import('../industryBlueprintRegistry.js').IndustryBlueprint} IndustryBlueprint */

/** @type {Record<string, IndustryBlueprint>} */
export const SERVICES_BLUEPRINTS = {
  'services.handyman': {
    id: 'services.handyman',
    industry: 'home_services',
    label: 'Handyman & Home Maintenance',
    verticalSlugs: ['services.handyman', 'services.home_services'],
    matchPatterns: [
      /\b(handyman|handy[\s-]?man|handyperson|odd[\s-]?jobs?|property maintenance|home maintenance|general maintenance|fix[\s-]?it)\b/i,
    ],
    templateKey: 'home_services',
    categories: [
      { key: 'repairs', label: 'General Repairs' },
      { key: 'painting', label: 'Painting & Walls' },
      { key: 'assembly', label: 'Assembly & Installation' },
      { key: 'outdoor', label: 'Outdoor & Cleaning' },
      { key: 'quotes', label: 'Inspections & Quotes' },
    ],
    imageQueryHints: {
      repairs: ['handyman home repair tools', 'contractor fixing door frame'],
      painting: ['painter rolling white wall interior', 'interior house painting'],
      assembly: ['furniture assembly ikea', 'tv wall mount living room'],
      outdoor: ['pressure washer cleaning driveway', 'window cleaner professional'],
      quotes: ['handyman consultation home visit', 'contractor measuring wall'],
    },
    items: [
      { categoryKey: 'repairs', name: 'Door Repair', description: 'Fix sticking doors, hinges, handles, and alignment issues.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 120, priceUnit: 'project', imageQueryHint: 'handyman repairing interior door hinge' },
      { categoryKey: 'repairs', name: 'Fence Repair', description: 'Timber and metal fence panel repairs, posts, and gates.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 180, priceUnit: 'project', imageQueryHint: 'repairing timber fence panel' },
      { categoryKey: 'repairs', name: 'Deck Maintenance', description: 'Board replacement, sanding, oiling, and structural checks.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 250, priceUnit: 'project', imageQueryHint: 'deck maintenance timber staining' },
      { categoryKey: 'repairs', name: 'Tile Repair', description: 'Replace cracked tiles and re-grout small affected areas.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 160, priceUnit: 'project', imageQueryHint: 'tile repair bathroom grout' },
      { categoryKey: 'repairs', name: 'Flyscreen Repair', description: 'Rescreen windows and doors with new mesh and frames.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 95, priceUnit: 'project', imageQueryHint: 'flyscreen window repair mesh' },
      { categoryKey: 'repairs', name: 'General Home Maintenance', description: 'Odd jobs, small fixes, and preventative upkeep around the home.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 80, priceUnit: 'hour', imageQueryHint: 'handyman toolbox home maintenance' },
      { categoryKey: 'painting', name: 'Interior Painting', description: 'Professional interior wall and ceiling painting with neat prep and finish.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 45, priceUnit: 'hour', imageQueryHint: 'painter rolling white wall interior room' },
      { categoryKey: 'painting', name: 'Plaster Wall Repair', description: 'Patch holes, cracks, and damaged plaster before painting.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 140, priceUnit: 'project', imageQueryHint: 'plaster wall repair patching' },
      { categoryKey: 'painting', name: 'Caulking & Sealing', description: 'Seal gaps around windows, wet areas, and skirting for a clean finish.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 90, priceUnit: 'project', imageQueryHint: 'caulking window frame sealing' },
      { categoryKey: 'painting', name: 'Picture Hanging', description: 'Secure mounting for artwork, mirrors, and shelves on any wall type.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 80, priceUnit: 'hour', durationMinutes: 60, imageQueryHint: 'hanging picture frame level wall' },
      { categoryKey: 'assembly', name: 'Furniture Assembly', description: 'Flat-pack and ready-to-assemble furniture built correctly and safely.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 90, priceUnit: 'hour', durationMinutes: 90, imageQueryHint: 'assembling ikea furniture home' },
      { categoryKey: 'assembly', name: 'Flat Pack Assembly', description: 'Wardrobes, desks, beds, and storage units assembled on site.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 95, priceUnit: 'hour', durationMinutes: 120, imageQueryHint: 'flat pack wardrobe assembly' },
      { categoryKey: 'assembly', name: 'TV Wall Mounting', description: 'Secure bracket install, cable tidy, and level mounting for any TV size.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 150, priceUnit: 'project', durationMinutes: 90, imageQueryHint: 'mounted television living room wall' },
      { categoryKey: 'assembly', name: 'Cabinet Installation', description: 'Kitchen, laundry, and storage cabinet mounting and alignment.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 200, priceUnit: 'project', imageQueryHint: 'kitchen cabinet installation handyman' },
      { categoryKey: 'assembly', name: 'Shelf Installation', description: 'Floating shelves and bracket systems fitted level and secure.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 85, priceUnit: 'hour', durationMinutes: 60, imageQueryHint: 'floating shelf installation wall' },
      { categoryKey: 'outdoor', name: 'Window Cleaning', description: 'Interior and exterior window cleaning for homes and small offices.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 120, priceUnit: 'project', durationMinutes: 90, imageQueryHint: 'professional window cleaner squeegee' },
      { categoryKey: 'outdoor', name: 'Pressure Washing', description: 'Driveways, paths, decks, and exterior surfaces restored with pressure wash.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 180, priceUnit: 'project', imageQueryHint: 'pressure washer cleaning driveway' },
      { categoryKey: 'outdoor', name: 'Gutter Cleaning', description: 'Clear blocked gutters and downpipes to protect your roofline.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 150, priceUnit: 'project', durationMinutes: 120, imageQueryHint: 'gutter cleaning ladder home' },
      { categoryKey: 'outdoor', name: 'Minor Plumbing Repairs', description: 'Leaking taps, loose fittings, and minor plumbing fixes where permitted.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 110, priceUnit: 'hour', imageQueryHint: 'handyman fixing leaking tap' },
      { categoryKey: 'outdoor', name: 'Minor Electrical Assistance', description: 'Light fittings, switch plates, and minor electrical tasks where permitted.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 110, priceUnit: 'hour', imageQueryHint: 'electrician changing light fitting home' },
      { categoryKey: 'quotes', name: 'Free Inspection', description: 'On-site visit to assess scope and provide a clear written quote.', serviceMode: 'fixed_booking', pricingModel: 'fixed', basePrice: 0, durationMinutes: 30, estimateDurationLabel: 'Free inspection', imageQueryHint: 'handyman home inspection clipboard' },
      { categoryKey: 'quotes', name: 'Request Quote', description: 'Tell us what you need and we will provide a detailed estimate.', serviceMode: 'quote_required', pricingModel: 'custom', estimateDurationLabel: 'Quote within 24 hours', imageQueryHint: 'contractor quote estimate home' },
      { categoryKey: 'quotes', name: 'Emergency Call-out', description: 'Priority attendance for urgent repairs when available.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 150, priceUnit: 'callout', estimateDurationLabel: 'Same-day when available', imageQueryHint: 'emergency home repair service van' },
    ],
    promptHints:
      'Generate a realistic handyman / home maintenance service catalog. Use specific trade service names. Pricing should be estimate-required, from-price, or per hour — never retail variants like Size S or Variant B.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Reliable workmanship', description: 'Experienced help for repairs, assembly, and maintenance.' },
        { icon: '⚡', label: 'Fast response', description: 'Book a visit or request a quote — we aim for same-week service.' },
        { icon: '♥', label: 'Home-focused care', description: 'Practical solutions tailored to your property and budget.' },
      ],
      heroImageKeywords: ['handyman home repair tools', 'contractor fixing wall interior', 'home maintenance service'],
      ctaLabel: 'Request quote',
    },
  },
  'services.cleaning': {
    id: 'services.cleaning',
    industry: 'cleaning',
    label: 'Cleaning Services',
    verticalSlugs: ['services.cleaning'],
    templateKey: 'home_services',
    categories: [
      { key: 'home', label: 'Home Cleaning' },
      { key: 'commercial', label: 'Commercial Cleaning' },
      { key: 'specialist', label: 'Specialist Cleaning' },
      { key: 'quotes', label: 'Quotes & Booking' },
    ],
    imageQueryHints: {
      home: ['house cleaning professional', 'vacuum cleaner home interior'],
      commercial: ['office cleaning team', 'commercial cleaning service'],
      specialist: ['carpet steam cleaning', 'window cleaning professional'],
      quotes: ['cleaning service quote clipboard'],
    },
    items: [
      { categoryKey: 'home', name: 'Regular House Clean', description: 'Weekly or fortnightly home cleaning tailored to your rooms.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 120, priceUnit: 'visit' },
      { categoryKey: 'home', name: 'Deep Clean', description: 'Detailed top-to-bottom clean including kitchens and bathrooms.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 250, priceUnit: 'project' },
      { categoryKey: 'home', name: 'End of Lease Clean', description: 'Bond-ready clean meeting agent inspection standards.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 320, priceUnit: 'project' },
      { categoryKey: 'commercial', name: 'Office Cleaning', description: 'Scheduled office and workspace cleaning after hours.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 180, priceUnit: 'visit' },
      { categoryKey: 'specialist', name: 'Carpet Steam Clean', description: 'Deep steam clean for carpets, rugs, and upholstery.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 140, priceUnit: 'room' },
      { categoryKey: 'specialist', name: 'Window Cleaning', description: 'Interior and exterior window cleaning for homes and offices.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 120, priceUnit: 'project' },
      { categoryKey: 'quotes', name: 'Free Quote', description: 'Walk-through and written quote for your cleaning needs.', serviceMode: 'fixed_booking', pricingModel: 'fixed', basePrice: 0 },
      { categoryKey: 'quotes', name: 'One-off Clean', description: 'Single visit for events, move-in, or seasonal refresh.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 160, priceUnit: 'visit' },
    ],
    promptHints: 'Generate realistic cleaning service names with per-visit or per-project pricing.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Trusted cleaners', description: 'Reliable teams for homes and workplaces.' },
        { icon: '⚡', label: 'Flexible scheduling', description: 'Book regular cleans or one-off deep cleans.' },
        { icon: '♥', label: 'Spotless results', description: 'Detailed cleaning with attention to high-touch areas.' },
      ],
      heroImageKeywords: ['professional house cleaning', 'clean modern home interior'],
      ctaLabel: 'Book service',
    },
  },
  'services.plumbing': {
    id: 'services.plumbing',
    industry: 'plumbing',
    label: 'Plumbing',
    verticalSlugs: ['services.plumbing'],
    templateKey: 'home_services',
    categories: [
      { key: 'repairs', label: 'Repairs' },
      { key: 'install', label: 'Installations' },
      { key: 'hotwater', label: 'Hot Water' },
      { key: 'quotes', label: 'Inspections & Quotes' },
    ],
    imageQueryHints: {
      repairs: ['plumber fixing leaking tap', 'blocked drain repair'],
      install: ['bathroom tap installation', 'toilet installation plumber'],
      hotwater: ['hot water system installation', 'plumber servicing hot water unit'],
      quotes: ['plumber inspection quote home'],
    },
    items: [
      { categoryKey: 'repairs', name: 'Blocked Drain', description: 'Clear blocked sinks, showers, and sewer lines.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 150, priceUnit: 'callout' },
      { categoryKey: 'repairs', name: 'Leaking Tap Repair', description: 'Fix dripping taps, washers, and cartridge replacements.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 120, priceUnit: 'service' },
      { categoryKey: 'repairs', name: 'Toilet Repair', description: 'Running cisterns, leaks, and flush mechanism fixes.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 140, priceUnit: 'service' },
      { categoryKey: 'repairs', name: 'Burst Pipe Emergency', description: 'Emergency attendance for burst pipes and major leaks.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 200, priceUnit: 'callout' },
      { categoryKey: 'install', name: 'Tap Replacement', description: 'Supply and install kitchen or bathroom taps.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 180, priceUnit: 'service' },
      { categoryKey: 'install', name: 'Toilet Installation', description: 'Remove old toilet and install a new suite.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 350, priceUnit: 'project' },
      { categoryKey: 'install', name: 'Dishwasher Plumbing', description: 'Connect dishwasher water and waste lines.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 160, priceUnit: 'service' },
      { categoryKey: 'hotwater', name: 'Hot Water System Service', description: 'Annual service and safety check for hot water units.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 180, priceUnit: 'service' },
      { categoryKey: 'hotwater', name: 'Hot Water Replacement', description: 'Remove and replace electric or gas hot water systems.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 1200, priceUnit: 'project' },
      { categoryKey: 'quotes', name: 'Plumbing Inspection', description: 'Full property plumbing check with written report.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 150, priceUnit: 'inspection' },
      { categoryKey: 'quotes', name: 'Free Quote', description: 'On-site quote for renovations and new installations.', serviceMode: 'fixed_booking', pricingModel: 'fixed', basePrice: 0 },
    ],
    promptHints: 'Generate realistic plumbing services: drains, taps, toilets, hot water. Use call-out and from-price models.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Licensed plumbers', description: 'Repairs and installations done to code.' },
        { icon: '⚡', label: 'Emergency call-outs', description: 'Fast response for urgent leaks and blockages.' },
        { icon: '♥', label: 'Clear pricing', description: 'Upfront quotes before work begins.' },
      ],
      heroImageKeywords: ['plumber fixing sink', 'professional plumbing service'],
      ctaLabel: 'Request quote',
    },
  },
  'services.electrician': {
    id: 'services.electrician',
    industry: 'electrical',
    label: 'Electrician',
    verticalSlugs: ['services.electrician'],
    templateKey: 'home_services',
    categories: [
      { key: 'general', label: 'General Electrical' },
      { key: 'lighting', label: 'Lighting' },
      { key: 'safety', label: 'Safety & Compliance' },
      { key: 'quotes', label: 'Quotes & Inspections' },
    ],
    imageQueryHints: {
      general: ['electrician installing power point', 'electrical wiring home'],
      lighting: ['pendant light installation', 'led downlight installation'],
      safety: ['switchboard upgrade electrician', 'smoke alarm installation'],
      quotes: ['electrician home inspection quote'],
    },
    items: [
      { categoryKey: 'general', name: 'Power Point Installation', description: 'Add or relocate power points safely and to code.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 150, priceUnit: 'point' },
      { categoryKey: 'general', name: 'Light Switch Replacement', description: 'Replace faulty or outdated switches and dimmers.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 95, priceUnit: 'service' },
      { categoryKey: 'general', name: 'Ceiling Fan Installation', description: 'Supply and install ceiling fans with balancing.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 180, priceUnit: 'fan' },
      { categoryKey: 'lighting', name: 'Downlight Installation', description: 'LED downlight supply and install with clean finish.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 85, priceUnit: 'light' },
      { categoryKey: 'lighting', name: 'Pendant Light Install', description: 'Mount pendant and chandelier fittings.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 120, priceUnit: 'service' },
      { categoryKey: 'lighting', name: 'Outdoor Lighting', description: 'Security and garden lighting installation.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 200, priceUnit: 'project' },
      { categoryKey: 'safety', name: 'Switchboard Upgrade', description: 'Modern safety switch and circuit breaker upgrades.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 800, priceUnit: 'project' },
      { categoryKey: 'safety', name: 'Smoke Alarm Compliance', description: 'Interconnected smoke alarm install to current standards.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 150, priceUnit: 'property' },
      { categoryKey: 'safety', name: 'Safety Inspection', description: 'Electrical safety check with compliance report.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 180, priceUnit: 'inspection' },
      { categoryKey: 'quotes', name: 'Free Quote', description: 'Written quote for electrical upgrades and renovations.', serviceMode: 'fixed_booking', pricingModel: 'fixed', basePrice: 0 },
    ],
    promptHints: 'Generate licensed electrician services: power points, lighting, switchboards, compliance.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Licensed electricians', description: 'Safe, compliant electrical work for homes and businesses.' },
        { icon: '⚡', label: 'Modern solutions', description: 'LED lighting, fans, and switchboard upgrades.' },
        { icon: '♥', label: 'Safety first', description: 'Inspections and compliance certificates available.' },
      ],
      heroImageKeywords: ['electrician installing light fixture', 'electrical service home'],
      ctaLabel: 'Book inspection',
    },
  },
  'services.construction': {
    id: 'services.construction',
    industry: 'construction',
    label: 'Construction & Renovation',
    verticalSlugs: ['services.construction'],
    templateKey: 'home_services',
    categories: [
      { key: 'renovation', label: 'Renovations' },
      { key: 'building', label: 'Building' },
      { key: 'trades', label: 'Trade Services' },
      { key: 'quotes', label: 'Quotes & Planning' },
    ],
    items: [
      { categoryKey: 'renovation', name: 'Bathroom Renovation', description: 'Full bathroom strip-out, waterproofing, and fit-out.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 15000, priceUnit: 'project' },
      { categoryKey: 'renovation', name: 'Kitchen Renovation', description: 'Cabinetry, benchtops, plumbing, and electrical coordination.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 20000, priceUnit: 'project' },
      { categoryKey: 'building', name: 'Home Extension', description: 'Design and build additional living space.', serviceMode: 'quote_required', pricingModel: 'custom' },
      { categoryKey: 'building', name: 'Deck Construction', description: 'Timber or composite deck design and build.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 8000, priceUnit: 'project' },
      { categoryKey: 'trades', name: 'Carpentry', description: 'Framing, architraves, skirting, and custom timber work.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 75, priceUnit: 'hour' },
      { categoryKey: 'trades', name: 'Plastering', description: 'New walls, repairs, and smooth finish plastering.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 45, priceUnit: 'hour' },
      { categoryKey: 'quotes', name: 'Site Consultation', description: 'On-site scope review and preliminary estimate.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 150, priceUnit: 'visit' },
      { categoryKey: 'quotes', name: 'Detailed Quote', description: 'Itemised quote for renovation or build project.', serviceMode: 'quote_required', pricingModel: 'custom' },
    ],
    promptHints: 'Generate construction and renovation services with project-based and hourly pricing.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Quality builds', description: 'Renovations and extensions managed start to finish.' },
        { icon: '⚡', label: 'Coordinated trades', description: 'One team for carpentry, plastering, and fit-out.' },
        { icon: '♥', label: 'Transparent quotes', description: 'Detailed scopes before work commences.' },
      ],
      heroImageKeywords: ['home renovation construction', 'builder on site'],
      ctaLabel: 'Request quote',
    },
  },
  'services.photography': {
    id: 'services.photography',
    industry: 'photography',
    label: 'Photography',
    verticalSlugs: ['services.photography'],
    templateKey: 'home_services',
    categories: [
      { key: 'portraits', label: 'Portraits' },
      { key: 'events', label: 'Events' },
      { key: 'commercial', label: 'Commercial' },
      { key: 'packages', label: 'Packages' },
    ],
    items: [
      { categoryKey: 'portraits', name: 'Individual Portrait Session', description: '1-hour studio or location portrait session with edited images.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 250, priceUnit: 'session' },
      { categoryKey: 'portraits', name: 'Family Portrait Session', description: 'Up to 5 people — outdoor or studio with 20 edited photos.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 350, priceUnit: 'session' },
      { categoryKey: 'events', name: 'Wedding Photography', description: 'Full-day coverage with highlight gallery and print rights.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 2500, priceUnit: 'event' },
      { categoryKey: 'events', name: 'Event Coverage', description: 'Corporate events, parties, and functions — hourly coverage.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 180, priceUnit: 'hour' },
      { categoryKey: 'commercial', name: 'Product Photography', description: 'Studio product shots for e-commerce and catalogues.', serviceMode: 'quote_required', pricingModel: 'from_price', fromPrice: 400, priceUnit: 'half-day' },
      { categoryKey: 'commercial', name: 'Headshots', description: 'Professional headshots for LinkedIn and team pages.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 180, priceUnit: 'person' },
      { categoryKey: 'packages', name: 'Mini Session', description: '20-minute mini session — ideal for updated portraits.', serviceMode: 'fixed_booking', pricingModel: 'from_price', fromPrice: 120, priceUnit: 'session' },
    ],
    promptHints: 'Generate photography packages with session, hourly, and event pricing.',
    websiteCopy: {
      uspItems: [
        { icon: '✦', label: 'Professional imagery', description: 'Portraits, events, and commercial photography.' },
        { icon: '⚡', label: 'Fast turnaround', description: 'Edited galleries delivered promptly.' },
        { icon: '♥', label: 'Personal approach', description: 'Relaxed sessions that capture authentic moments.' },
      ],
      heroImageKeywords: ['professional photographer portrait session', 'camera studio photography'],
      ctaLabel: 'Book session',
    },
  },
};
