/**
 * Tool Registry - centralized definitions for mission pipeline tools.
 * Step names (e.g. generate_tags) must exist here; buildDefaultMissionSteps validates against it.
 */

const TOOLS = [
  { toolName: 'analyze_store', label: 'Analyze store', description: 'Analyze store data and structure', category: 'store', targetTypes: ['store', 'draft_store'], requiresConfirmation: false, aliases: ['analyze'] },
  { toolName: 'generate_tags', label: 'Generate tags', description: 'Generate product or category tags', category: 'store', targetTypes: ['store', 'draft_store'], requiresConfirmation: false, aliases: ['tags'] },
  { toolName: 'rewrite_descriptions', label: 'Rewrite descriptions', description: 'Rewrite product or store descriptions', category: 'store', targetTypes: ['store', 'draft_store'], requiresConfirmation: false, aliases: ['rewrite'] },
  { toolName: 'improve_hero', label: 'Improve hero', description: 'Improve store hero image or section', category: 'store', targetTypes: ['store', 'draft_store'], requiresConfirmation: false, aliases: ['hero'] },
  {
    toolName: 'upload_store_asset',
    label: 'Upload store asset',
    description: 'Logo, avatar, or hero upload intent from Performer / intake classifier',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
  },
  {
    toolName: 'replace_store_catalog',
    label: 'Replace store catalog',
    description: 'Replace draft catalog with real menu or products',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
  },
  {
    toolName: 'update_store_hero',
    label: 'Update store hero',
    description: 'Change storefront hero or banner image from natural language',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
  },
  {
    toolName: 'setBusinessSocialLinks',
    label: 'Set business social links',
    description: 'Set or update social network profile links for a business (Instagram, Facebook, TikTok, X, YouTube, LinkedIn, WhatsApp)',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    aliases: ['set_business_social_links'],
  },
  {
    toolName: 'update_brand_kit',
    label: 'Update brand kit',
    description: 'Update store brand kit tone, style, and color palette for media search enrichment',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
  },
  { toolName: 'market_research', label: 'Market research', description: 'Run researcher agent for market report (AU focus)', category: 'store', targetTypes: ['store', 'draft_store'], requiresConfirmation: false, aliases: ['campaign_research'] },
  { toolName: 'consensus', label: 'Consensus', description: 'Run three voter agents on market report and resolve approve/revise/hold', category: 'store', targetTypes: ['store', 'draft_store'], requiresConfirmation: false },
  { toolName: 'create_promotion', label: 'Create promotion', description: 'Create a promotion', category: 'promotion', targetTypes: ['promotion'], requiresConfirmation: false, aliases: ['generate_mini_website', 'mini_website'] },
  { toolName: 'launch_campaign', label: 'Launch campaign', description: 'Deploy promotion to channels (landing page, WhatsApp, social)', category: 'promotion', targetTypes: ['promotion'], requiresConfirmation: false },
  { toolName: 'publish_to_social', label: 'Share campaign', description: 'Share or post a campaign to social platforms (share links or connected Facebook Page)', category: 'promotion', targetTypes: ['promotion', 'store'], requiresConfirmation: true },
  { toolName: 'connect_social_account', label: 'Connect social account', description: 'Link Facebook Page via OAuth for automatic posting', category: 'promotion', targetTypes: ['store', 'promotion'], requiresConfirmation: false },
  { toolName: 'edit_artifact', label: 'Edit artifact copy', description: 'LLM-assisted edits to promotion, business profile, storefront hero, or mini-website draft preview', category: 'content', targetTypes: ['store', 'draft_store', 'promotion'], requiresConfirmation: false },
  { toolName: 'generate_promotion_asset', label: 'Generate promotion asset', description: 'Generate assets for promotion', category: 'promotion', targetTypes: ['promotion'], requiresConfirmation: false },
  { toolName: 'assign_promotion_slot', label: 'Assign promotion slot', description: 'Assign promotion to slot', category: 'promotion', targetTypes: ['promotion', 'slot_assignment'], requiresConfirmation: false },
  {
    toolName: 'activate_promotion',
    label: 'Activate promotion',
    description: 'Activate promotion',
    category: 'promotion',
    targetTypes: ['promotion'],
    requiresConfirmation: false,
    aliases: ['show_promotion', 'display_promotion', 'publish_promotion', 'show_promo'],
  },
  { toolName: 'content_creator', label: 'Content creator', description: 'Generate campaign content (social, email, promo copy)', category: 'content', targetTypes: ['store', 'draft_store'], requiresConfirmation: false, aliases: ['content'] },
  { toolName: 'crm', label: 'CRM', description: 'Log leads and customer interactions from campaign', category: 'crm', targetTypes: ['store'], requiresConfirmation: false },
  { toolName: 'resolve_target_screens', label: 'Resolve target screens', description: 'Resolve target screens for deployment', category: 'devices', targetTypes: ['device_group'], requiresConfirmation: false },
  { toolName: 'prepare_screen_asset', label: 'Prepare screen asset', description: 'Prepare asset for screen', category: 'content', targetTypes: ['device_group'], requiresConfirmation: false },
  { toolName: 'assign_screen_slot', label: 'Assign screen slot', description: 'Assign content to screen slot', category: 'devices', targetTypes: ['device_group', 'slot_assignment'], requiresConfirmation: false },
  { toolName: 'activate_screen_content', label: 'Activate screen content', description: 'Activate screen content', category: 'content', targetTypes: ['device_group'], requiresConfirmation: false },
  { toolName: 'generate_social_posts', label: 'Generate social posts', description: 'Generate social media posts for your store', category: 'content', targetTypes: ['store', 'draft_store'], requiresConfirmation: false, aliases: ['social_posts'] },
  { toolName: 'smart_visual', label: 'Smart visual', description: 'Generate images or moodboards from a text prompt (intake / campaigns)', category: 'content', targetTypes: ['store', 'draft_store', 'promotion'], requiresConfirmation: false },
  { toolName: 'create_offer', label: 'Create offer', description: 'Create an offer and optional promotion', category: 'promotion', targetTypes: ['promotion'], requiresConfirmation: false },
  { toolName: 'create_offer_draft', label: 'Create offer draft', description: 'Build a read-only first-offer draft artifact (no publish)', category: 'promotion', targetTypes: ['store', 'draft_store'], requiresConfirmation: true },
  { toolName: 'revise_offer_draft', label: 'Revise offer draft', description: 'Create a new offer draft version from revision notes (no publish)', category: 'promotion', targetTypes: ['store', 'draft_store'], requiresConfirmation: true },
  { toolName: 'mini_website_get_sections', label: 'Load mini website sections', description: 'Read published mini website sections and theme for a store', category: 'store', targetTypes: ['store', 'draft_store'], requiresConfirmation: false },
  { toolName: 'generate_section_patches', label: 'Plan section edits', description: 'LLM: minimal section patches from user intent', category: 'store', targetTypes: ['store', 'draft_store'], requiresConfirmation: false },
  { toolName: 'mini_website_patch_sections', label: 'Apply mini website patches', description: 'Merge patches into mini website and save', category: 'store', targetTypes: ['store', 'draft_store'], requiresConfirmation: false },
  { toolName: 'propose_website_patch', label: 'Review proposed website changes', description: 'Emit patch proposal and pause for user approval', category: 'store', targetTypes: ['store', 'draft_store'], requiresConfirmation: false },
  { toolName: 'change_hero_headline', label: 'Change hero headline', description: 'Update mini-website hero headline/subheadline', category: 'store', targetTypes: ['store', 'draft_store'], requiresConfirmation: false },
  { toolName: 'device.sendInput', label: 'Desktop device control', description: 'Send a desktop automation task to SuperCopilot', category: 'devices', targetTypes: ['generic'], requiresConfirmation: true },
  { toolName: 'signage.list-devices', label: 'List C-Net screens', description: 'List paired store screens and current playlist', category: 'devices', targetTypes: ['store', 'draft_store'], requiresConfirmation: false },
  { toolName: 'signage.publish-to-devices', label: 'Push playlist to screens', description: 'Push a SIGNAGE playlist to selected or all store screens', category: 'devices', targetTypes: ['store', 'draft_store'], requiresConfirmation: false },
  { toolName: 'mcp_context_products', label: 'MCP product context', description: 'Read-only published products via MCP adapter (runtime smoke / context)', category: 'mcp', targetTypes: ['store', 'draft_store', 'generic'], requiresConfirmation: false },
  { toolName: 'mcp_context_business', label: 'MCP business context', description: 'Read-only business/store summaries via MCP adapter (runtime smoke / context)', category: 'mcp', targetTypes: ['store', 'draft_store', 'generic'], requiresConfirmation: false },
  { toolName: 'mcp_context_store_assets', label: 'MCP store assets context', description: 'Read-only branding and asset metadata via MCP adapter (runtime smoke / context)', category: 'mcp', targetTypes: ['store', 'draft_store', 'generic'], requiresConfirmation: false },
  { toolName: 'mcp_context_promotions', label: 'MCP promotions context', description: 'Read-only active promotions for a store via MCP adapter', category: 'mcp', targetTypes: ['store', 'draft_store', 'generic'], requiresConfirmation: false },
  { toolName: 'mcp_context_missions', label: 'MCP missions context', description: 'Read-only recent mission pipeline history via MCP adapter', category: 'mcp', targetTypes: ['store', 'draft_store', 'generic'], requiresConfirmation: false },
  { toolName: 'mcp_context_analytics', label: 'MCP analytics context', description: 'Read-only store activity counts via MCP adapter', category: 'mcp', targetTypes: ['store', 'draft_store', 'generic'], requiresConfirmation: false },
  {
    toolName: 'mcp_google_calendar_create_event',
    label: 'Google Calendar: create event',
    description: 'Create a calendar event via Google Calendar API (OAuthConnection platform google)',
    category: 'mcp',
    targetTypes: ['store', 'draft_store', 'generic'],
    requiresConfirmation: true,
  },
  { toolName: 'start_build_store', label: 'Start build store', description: 'Create orchestrator build_store job and draft (AI operator)', category: 'operator', targetTypes: ['generic'], requiresConfirmation: false },
  { toolName: 'get_draft_by_run', label: 'Get draft by run', description: 'Resolve draft id by generationRunId (AI operator)', category: 'operator', targetTypes: ['generic'], requiresConfirmation: false },
  { toolName: 'get_draft_summary', label: 'Get draft summary', description: 'Draft status and catalog counts (AI operator)', category: 'operator', targetTypes: ['generic'], requiresConfirmation: false },
  { toolName: 'poll_orchestra_job', label: 'Poll orchestra job', description: 'Read orchestrator task status and result (AI operator)', category: 'operator', targetTypes: ['generic'], requiresConfirmation: false },
  { toolName: 'publish_store', label: 'Publish store from draft', description: 'Commit draft to published store (AI operator)', category: 'operator', targetTypes: ['generic'], requiresConfirmation: false },
  { toolName: 'log_event', label: 'Log event', description: 'Append operator log line (AI operator)', category: 'operator', targetTypes: ['generic'], requiresConfirmation: false },
  { toolName: 'run_pipeline', label: 'Run pipeline', description: 'Run full build_store pipeline in one tool (AI operator)', category: 'operator', targetTypes: ['generic'], requiresConfirmation: false },
  {
    toolName: 'mission_pipeline_stub',
    label: 'Pipeline branch stub',
    description: 'Internal: records a conditional branch without side effects (Phase 3 checkpoints)',
    category: 'operator',
    targetTypes: ['generic', 'store', 'draft_store'],
    requiresConfirmation: false,
  },
  {
    toolName: 'structured_store_build',
    label: 'Structured store build',
    description: 'After checkpoints: create DraftStore, generate preview, commit Business for authed users',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
  },
  {
    toolName: 'video_generate_multimodal',
    label: 'Generate video',
    description: 'Create or deliver a multimodal video asset (async SSE artifact to console)',
    category: 'content',
    targetTypes: ['store', 'draft_store', 'promotion', 'generic'],
    requiresConfirmation: false,
  },
  {
    toolName: 'search_hero_media',
    label: 'Search hero media',
    description:
      'Search for hero images or videos across multiple media providers (Pexels, Coverr, Pixabay, Mixkit). Use when the user wants to find media for their store hero section.',
    category: 'content',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      query: { type: 'string', required: true },
      mediaType: { type: 'string', required: false },
      storeId: { type: 'string', required: false },
      perPage: { type: 'number', required: false },
    },
  },
  {
    toolName: 'create_campaign_brief',
    label: 'Create campaign brief',
    description: 'Define structured campaign intent, target audience, offer, and tone',
    category: 'campaign',
    targetTypes: ['store', 'draft_store', 'promotion'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      objective: { type: 'string', required: false },
      targetAudience: { type: 'string', required: false },
      offer: { type: 'string', required: false },
      duration: { type: 'string', required: false },
      tone: { type: 'string', required: false },
    },
  },
  {
    toolName: 'generate_campaign_graphics',
    label: 'Generate campaign graphics',
    description: 'Find stock images or videos matched to a campaign brief and brand style',
    category: 'campaign',
    targetTypes: ['store', 'draft_store', 'promotion'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      brief: { type: 'object', required: false },
      style: { type: 'string', required: false },
      mediaType: { type: 'string', required: false },
    },
  },
  {
    toolName: 'generate_campaign_copy',
    label: 'Generate campaign copy',
    description: 'Write headlines, captions, CTAs, and platform variants for a campaign brief',
    category: 'campaign',
    targetTypes: ['store', 'draft_store', 'promotion'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      brief: { type: 'object', required: false },
      tone: { type: 'string', required: false },
      platforms: { type: 'array', required: false },
    },
  },
  {
    toolName: 'qa_campaign_package',
    label: 'QA campaign package',
    description: 'Validate campaign brief, graphics, and copy before packaging',
    category: 'campaign',
    targetTypes: ['store', 'draft_store', 'promotion'],
    requiresConfirmation: false,
    parameters: {
      brief: { type: 'object', required: false },
      graphics: { type: 'array', required: false },
      copy: { type: 'object', required: false },
    },
  },
  {
    toolName: 'package_campaign_artifact',
    label: 'Package campaign artifact',
    description: 'Bundle brief, graphics, copy, and optional slideshow into a publishable campaign artifact',
    category: 'campaign',
    targetTypes: ['store', 'draft_store', 'promotion'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      brief: { type: 'object', required: false },
      graphics: { type: 'array', required: false },
      copy: { type: 'object', required: false },
      slideshowId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'select_display_content',
    label: 'Select display content',
    description: 'Choose campaign artifact, hero, slideshow, or product content for in-store display',
    category: 'display',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      contentType: { type: 'string', required: false },
      artifactId: { type: 'string', required: false },
      campaignId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'format_for_display',
    label: 'Format for display',
    description: 'Adapt content to screen aspect ratio, slide duration, loop, and transition settings',
    category: 'display',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      content: { type: 'object', required: false },
      displayProfile: { type: 'object', required: false },
    },
  },
  {
    toolName: 'push_to_display_device',
    label: 'Push to display device',
    description: 'Send formatted content to a paired in-store display screen',
    category: 'display',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      deviceId: { type: 'string', required: false },
      storeId: { type: 'string', required: false },
      formatted: { type: 'object', required: false },
    },
  },
  {
    toolName: 'verify_display_output',
    label: 'Verify display output',
    description: 'Confirm a display device received content and is playing',
    category: 'display',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      deviceId: { type: 'string', required: false },
      contentId: { type: 'string', required: false },
      pushResult: { type: 'object', required: false },
    },
  },
  {
    toolName: 'analyze_offer_performance',
    label: 'Analyze offer performance',
    description: 'Read offer or campaign metrics over a lookback window and identify weak points',
    category: 'offer',
    targetTypes: ['store', 'draft_store', 'promotion'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      offerId: { type: 'string', required: false },
      campaignId: { type: 'string', required: false },
      lookbackDays: { type: 'number', required: false },
    },
  },
  {
    toolName: 'suggest_offer_improvements',
    label: 'Suggest offer improvements',
    description: 'Generate ranked optimization suggestions from performance analysis',
    category: 'offer',
    targetTypes: ['store', 'draft_store', 'promotion'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      analysis: { type: 'object', required: false },
      tone: { type: 'string', required: false },
      brandKit: { type: 'object', required: false },
    },
  },
  {
    toolName: 'apply_offer_optimization',
    label: 'Apply offer optimization',
    description: 'Apply a selected optimization suggestion with optional user confirmation',
    category: 'offer',
    targetTypes: ['store', 'draft_store', 'promotion'],
    requiresConfirmation: true,
    parameters: {
      storeId: { type: 'string', required: false },
      offerId: { type: 'string', required: false },
      suggestion: { type: 'object', required: false },
      confirmed: { type: 'boolean', required: false },
    },
  },
  {
    toolName: 'track_offer_outcome',
    label: 'Track offer outcome',
    description: 'Record optimization baseline metrics and schedule next performance review',
    category: 'offer',
    targetTypes: ['store', 'draft_store', 'promotion'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      offerId: { type: 'string', required: false },
      optimizationId: { type: 'string', required: false },
      baselineMetrics: { type: 'object', required: false },
      suggestion: { type: 'object', required: false },
    },
  },
  {
    toolName: 'audit_local_presence',
    label: 'Audit local presence',
    description: 'Assess store local visibility, content freshness, offers, social links, and display presence',
    category: 'growth',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      includeCompetitors: { type: 'boolean', required: false },
    },
  },
  {
    toolName: 'generate_growth_plan',
    label: 'Generate growth plan',
    description: 'Create ranked local growth actions from a presence audit',
    category: 'growth',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      audit: { type: 'object', required: false },
      businessType: { type: 'string', required: false },
      goals: { type: 'array', required: false },
    },
  },
  {
    toolName: 'monitor_growth_baseline',
    label: 'Monitor growth baseline',
    description: 'Record growth audit scores and schedule the next local presence review',
    category: 'growth',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      audit: { type: 'object', required: false },
      planId: { type: 'string', required: false },
      actionTaken: { type: 'string', required: false },
    },
  },
  {
    toolName: 'check_booking_availability',
    label: 'Check booking availability',
    description: 'Find open appointment slots for a store on a given date',
    category: 'booking',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      serviceType: { type: 'string', required: false },
      date: { type: 'string', required: false },
      duration: { type: 'number', required: false },
      partySize: { type: 'number', required: false },
    },
  },
  {
    toolName: 'create_booking_record',
    label: 'Create booking record',
    description: 'Reserve an available slot and create a confirmed booking',
    category: 'booking',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      storeId: { type: 'string', required: false },
      slotId: { type: 'string', required: false },
      customerName: { type: 'string', required: false },
      customerPhone: { type: 'string', required: false },
      customerEmail: { type: 'string', required: false },
      serviceType: { type: 'string', required: false },
      notes: { type: 'string', required: false },
    },
  },
  {
    toolName: 'confirm_booking_customer',
    label: 'Confirm booking customer',
    description: 'Send booking confirmation message to the customer',
    category: 'booking',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      booking: { type: 'object', required: false },
      channel: { type: 'string', required: false },
    },
  },
  {
    toolName: 'schedule_booking_reminder',
    label: 'Schedule booking reminder',
    description: 'Queue a reminder notification before the appointment',
    category: 'booking',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      booking: { type: 'object', required: false },
      reminderLeadHours: { type: 'number', required: false },
    },
  },
  {
    toolName: 'handle_booking_outcome',
    label: 'Handle booking outcome',
    description: 'Resolve completed, cancelled, or no-show bookings with follow-up actions',
    category: 'booking',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    parameters: {
      bookingId: { type: 'string', required: false },
      outcome: { type: 'string', required: false },
      reason: { type: 'string', required: false },
      refund: { type: 'boolean', required: false },
    },
  },
  {
    toolName: 'generate_slideshow',
    label: 'Generate slideshow',
    description: 'Create a promotional slideshow artifact (async SSE delivery to console)',
    category: 'content',
    targetTypes: ['store', 'draft_store', 'promotion', 'generic'],
    requiresConfirmation: false,
  },
  {
    toolName: 'generate_poster',
    label: 'Generate poster',
    description: 'Create a promotional poster from store catalog, hero image, and templates',
    category: 'content',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    aliases: ['poster', 'flyer'],
  },
  {
    toolName: 'mutate_poster',
    label: 'Edit poster',
    description: 'Apply natural-language edits to a generated poster canvas (title, images, colors)',
    category: 'content',
    targetTypes: ['store', 'draft_store', 'generic'],
    requiresConfirmation: false,
  },

  // ─── i18n repair agent tools ──────────────────────────────────────────────
  {
    toolName: 'scanHardcodedStrings',
    label: 'Scan hardcoded strings',
    description: 'Scan a source file for hardcoded user-facing strings that bypass the i18n translation system',
    category: 'i18n',
    targetTypes: ['generic'],
    requiresConfirmation: false,
    aliases: ['scan_i18n', 'find_hardcoded'],
  },
  {
    toolName: 'checkI18nKey',
    label: 'Check i18n key',
    description: 'Check if a translation key exists in i18n.js for a given locale',
    category: 'i18n',
    targetTypes: ['generic'],
    requiresConfirmation: false,
  },
  {
    toolName: 'addI18nKey',
    label: 'Add i18n key',
    description: 'Add translation key with values for all active locales to i18n.js',
    category: 'i18n',
    targetTypes: ['generic'],
    requiresConfirmation: false,
    aliases: ['add_translation_key'],
  },
  {
    toolName: 'wireI18nString',
    label: 'Wire i18n string',
    description: 'Replace hardcoded string in a component with t() translation call',
    category: 'i18n',
    targetTypes: ['generic'],
    requiresConfirmation: false,
    aliases: ['wire_translation'],
  },
  {
    toolName: 'generateI18nKey',
    label: 'Generate i18n key',
    description: 'Derive camelCase key name and namespace from string value and file path',
    category: 'i18n',
    targetTypes: ['generic'],
    requiresConfirmation: false,
  },
  {
    toolName: 'translateString',
    label: 'Translate string',
    description: 'Translate UI string into target locales using Claude. Supports any language Claude supports.',
    category: 'i18n',
    targetTypes: ['generic'],
    requiresConfirmation: false,
    aliases: ['translate', 'get_translation'],
  },
  {
    toolName: 'runI18nTests',
    label: 'Run i18n tests',
    description: 'Run i18n test suite to confirm no regression after translation changes',
    category: 'i18n',
    targetTypes: ['generic'],
    requiresConfirmation: false,
  },
  {
    toolName: 'reportI18nProgress',
    label: 'Report i18n progress',
    description: 'Write i18n repair progress summary to MissionBlackboard',
    category: 'i18n',
    targetTypes: ['generic'],
    requiresConfirmation: false,
  },
  {
    toolName: 'audit_codebase',
    label: 'Audit codebase',
    description: 'Traces a runtime error to a source file and line.',
    category: 'maintenance',
    targetTypes: ['generic'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    missionTypes: ['MAINTENANCE'],
    requiresOperatorSession: true,
  },
  {
    toolName: 'propose_patch',
    label: 'Propose patch',
    description: 'Generates a before/after diff fix for a traced error.',
    category: 'maintenance',
    targetTypes: ['generic'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    missionTypes: ['MAINTENANCE'],
    requiresOperatorSession: true,
  },
  {
    toolName: 'apply_patch',
    label: 'Apply patch',
    description:
      'Atomically applies a proposed patch to a source file and logs to patches.audit.json.',
    category: 'maintenance',
    targetTypes: ['generic'],
    requiresConfirmation: true,
    riskLevel: 'state_change',
    missionTypes: ['MAINTENANCE'],
    requiresOperatorSession: true,
  },
  // DANH: skill-round4-registry
  {
    toolName: 'segment_loyal_customers',
    label: 'Segment loyal customers',
    description: 'Identify repeat customers from booking history',
    category: 'loyalty',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      storeId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'define_loyalty_tiers',
    label: 'Define loyalty tiers',
    description: 'Generate loyalty tier structure based on customer count',
    category: 'loyalty',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      storeId: { type: 'string', required: false },
      customerCount: { type: 'number', required: false },
    },
  },
  {
    toolName: 'create_loyalty_offer',
    label: 'Create loyalty offer',
    description: 'Generate loyalty offer copy per tier',
    category: 'loyalty',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      storeId: { type: 'string', required: false },
      tiers: { type: 'array', required: false },
      businessCategory: { type: 'string', required: false },
    },
  },
  {
    toolName: 'schedule_loyalty_campaign',
    label: 'Schedule loyalty campaign',
    description: 'Schedule loyalty campaign as a store promo draft',
    category: 'loyalty',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: true,
    riskLevel: 'state_change',
    parameters: {
      storeId: { type: 'string', required: false },
      offers: { type: 'array', required: false },
    },
  },
  {
    toolName: 'fetch_store_content',
    label: 'Fetch store content',
    description: 'Fetch current product names and descriptions for a store',
    category: 'content',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      storeId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'rewrite_content_copy',
    label: 'Rewrite content copy',
    description: 'Generate improved product description copy (max 3 products, no persist)',
    category: 'content',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      products: { type: 'array', required: false },
      brandTone: { type: 'string', required: false },
      businessCategory: { type: 'string', required: false },
    },
  },
  {
    toolName: 'generate_seo_tags',
    label: 'Generate SEO tags',
    description: 'Generate SEO tags for products and store',
    category: 'content',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      products: { type: 'array', required: false },
      businessCategory: { type: 'string', required: false },
      storeSlug: { type: 'string', required: false },
    },
  },
  {
    toolName: 'audit_hero_media',
    label: 'Audit hero media',
    description: 'Check current hero image/video state for a store',
    category: 'content',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      storeId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'suggest_hero_media',
    label: 'Suggest hero media',
    description: 'Suggest hero media search queries based on store category and style',
    category: 'content',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      category: { type: 'string', required: false },
      brandStyle: { type: 'string', required: false },
      storeName: { type: 'string', required: false },
    },
  },
  {
    toolName: 'identify_feature_target',
    label: 'Identify feature target',
    description: 'Identify which product to feature on homepage',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      storeId: { type: 'string', required: false },
      userMessage: { type: 'string', required: false },
    },
  },
  {
    toolName: 'apply_homepage_feature',
    label: 'Apply homepage feature',
    description: 'Apply featured flag to a product on homepage',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: true,
    riskLevel: 'state_change',
    parameters: {
      storeId: { type: 'string', required: false },
      productId: { type: 'string', required: false },
    },
  },
  // DANH: toolregistry-gap-fix
  {
    toolName: 'get_store_analytics',
    label: 'Get store analytics',
    description: 'Retrieve store performance metrics',
    category: 'analytics',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    requiresStore: true,
    parameters: {
      storeId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'generate_report_summary',
    label: 'Generate report summary',
    description: 'Generate insight summary from analytics',
    category: 'analytics',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      analytics: { type: 'object', required: false },
      storeId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'get_review_summary',
    label: 'Get review summary',
    description: 'Fetch store reviews summary',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    requiresStore: true,
    parameters: {
      storeId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'draft_review_response',
    label: 'Draft review response',
    description: 'Draft a suggested reply to a review',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      review: { type: 'object', required: false },
      storeName: { type: 'string', required: false },
      brandTone: { type: 'string', required: false },
    },
  },
  {
    toolName: 'audit_store_completeness',
    label: 'Audit store completeness',
    description: 'Audit store profile completeness',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    requiresStore: true,
    parameters: {
      storeId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'generate_health_report',
    label: 'Generate health report',
    description: 'Score store health and list fixes',
    category: 'store',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      score: { type: 'number', required: false },
      missing: { type: 'array', required: false },
      audit: { type: 'object', required: false },
      storeId: { type: 'string', required: false },
    },
  },
  // DANH: skill-round5-video
  {
    toolName: 'analyze_video_brief',
    label: 'Analyze video brief',
    description: 'Derive video style and keywords from store context',
    category: 'video',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      storeId: { type: 'string', required: false },
      userMessage: { type: 'string', required: false },
    },
  },
  {
    toolName: 'generate_video_script',
    label: 'Generate video script',
    description: 'Write a short promotional video script',
    category: 'video',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      style: { type: 'string', required: false },
      duration: { type: 'number', required: false },
      mood: { type: 'string', required: false },
      storeName: { type: 'string', required: false },
      brandTone: { type: 'string', required: false },
    },
  },
  {
    toolName: 'queue_video_generation',
    label: 'Queue video generation',
    description: 'Queue video render when VIDEO_API_KEY is configured',
    category: 'video',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      script: { type: 'string', required: false },
      style: { type: 'string', required: false },
    },
  },
  // DANH: skill-round5-cardscan
  {
    toolName: 'check_scan_capability',
    label: 'Check scan capability',
    description: 'Probe SuperCopilot bridge for card scan availability',
    category: 'scan',
    targetTypes: ['generic'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      userId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'extract_card_data',
    label: 'Extract card data',
    description: 'OCR business card via SuperCopilot bridge',
    category: 'scan',
    targetTypes: ['generic'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      available: { type: 'boolean', required: false },
      imageUrl: { type: 'string', required: false },
    },
  },
  {
    toolName: 'create_product_from_card',
    label: 'Create product from card',
    description: 'Create catalog product from scanned card data',
    category: 'scan',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: true,
    riskLevel: 'state_change',
    parameters: {
      extracted: { type: 'boolean', required: false },
      cardData: { type: 'object', required: false },
    },
  },
  // DANH: skill-round5-cnet
  {
    toolName: 'check_cnet_config',
    label: 'Check C-Net config',
    description: 'Verify C-Net API keys and endpoint',
    category: 'cnet',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      storeId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'prepare_cnet_payload',
    label: 'Prepare C-Net payload',
    description: 'Package store content for C-Net deployment',
    category: 'cnet',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      storeId: { type: 'string', required: false },
      configured: { type: 'boolean', required: false },
    },
  },
  {
    toolName: 'deploy_to_cnet',
    label: 'Deploy to C-Net',
    description: 'Push prepared payload to C-Net content network',
    category: 'cnet',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: true,
    riskLevel: 'state_change',
    parameters: {
      storeId: { type: 'string', required: false },
      configured: { type: 'boolean', required: false },
      payload: { type: 'object', required: false },
    },
  },
  // DANH: skill-round6-document
  {
    toolName: 'extract_document_data',
    label: 'Extract document data',
    description: 'Vision/OCR extraction of products, offers, and events from a business document image',
    category: 'document',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      imageUrl: { type: 'string', required: false },
      imageDataUrl: { type: 'string', required: false },
      documentUrl: { type: 'string', required: false },
      documentBase64: { type: 'string', required: false },
      mimeType: { type: 'string', required: false },
      extractedText: { type: 'string', required: false },
      businessName: { type: 'string', required: false },
    },
  },
  {
    toolName: 'create_products_from_document',
    label: 'Create products from document',
    description: 'Add catalog products from extracted document data',
    category: 'document',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: true,
    riskLevel: 'state_change',
    parameters: {
      storeId: { type: 'string', required: false },
      extracted: { type: 'boolean', required: false },
      data: { type: 'object', required: false },
    },
  },
  {
    toolName: 'create_promotions_from_document',
    label: 'Create promotions from document',
    description: 'Create store promotion drafts from extracted offers and events',
    category: 'document',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: true,
    riskLevel: 'state_change',
    parameters: {
      storeId: { type: 'string', required: false },
      extracted: { type: 'boolean', required: false },
      data: { type: 'object', required: false },
    },
  },
  {
    toolName: 'suggest_campaign_plan',
    label: 'Suggest campaign plan',
    description: 'Week-by-week content calendar leading up to document event dates',
    category: 'document',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      storeId: { type: 'string', required: false },
      missionId: { type: 'string', required: false },
      productIds: { type: 'array', required: false },
      extracted: { type: 'boolean', required: false },
      data: { type: 'object', required: false },
      businessName: { type: 'string', required: false },
    },
  },
  {
    toolName: 'generate_execution_summary',
    label: 'Generate execution summary',
    description: 'Compose Performer summary after document ingestion pipeline',
    category: 'document',
    targetTypes: ['store', 'draft_store'],
    requiresConfirmation: false,
    riskLevel: 'safe_read',
    parameters: {
      extractResult: { type: 'object', required: false },
      productsResult: { type: 'object', required: false },
      promosResult: { type: 'object', required: false },
      planResult: { type: 'object', required: false },
      livingDocResult: { type: 'object', required: false },
    },
  },
  {
    toolName: 'generate_living_document',
    label: 'Publish living document',
    description: 'Publish storefront / living document from ingested flyer data',
    category: 'document',
    targetTypes: ['store'],
    requiresConfirmation: false,
    riskLevel: 'state_change',
    parameters: {
      storeId: { type: 'string', required: true },
      extractResult: { type: 'object', required: false },
      missionId: { type: 'string', required: false },
    },
  },
  {
    toolName: 'activate_campaigns',
    label: 'Activate campaigns',
    description: 'Activate draft store promotions created from document ingestion',
    category: 'campaign',
    targetTypes: ['store'],
    requiresConfirmation: false,
    riskLevel: 'state_change',
    parameters: {
      storeId: { type: 'string', required: true },
    },
  },
];

// NOTE: Keep TOOLS stable for proactive runway contracts/tests. These internal
// tools are available for dispatch + executionGateway auth lookup, but they are
// not part of the proactive runway allowlist.
const INTERNAL_MAINTENANCE_TOOLS = [
  // file_read
  {
    toolName: 'file_read',
    label: 'File read',
    description: 'Reads a source file from the repo.',
    category: 'maintenance',
    targetTypes: ['generic'],
    riskLevel: 'safe_read',
    missionTypes: ['MAINTENANCE'],
    requiresConfirmation: false,
    requiresOperatorSession: true,
  },
  // file_write
  {
    toolName: 'file_write',
    label: 'File write',
    description: 'Writes content to a source file.',
    category: 'maintenance',
    targetTypes: ['generic'],
    riskLevel: 'state_change',
    missionTypes: ['MAINTENANCE'],
    requiresConfirmation: true,
    requiresOperatorSession: true,
  },
  // read_mission_log
  {
    toolName: 'read_mission_log',
    label: 'Read mission log',
    description: 'Reads mission execution logs from MissionBlackboard.',
    category: 'maintenance',
    targetTypes: ['generic'],
    riskLevel: 'safe_read',
    missionTypes: ['MAINTENANCE'],
    requiresConfirmation: false,
    requiresOperatorSession: true,
  },
  // restart_service
  {
    toolName: 'restart_service',
    label: 'Restart service',
    description: 'Restarts a backend service process.',
    category: 'maintenance',
    targetTypes: ['generic'],
    riskLevel: 'destructive',
    missionTypes: ['MAINTENANCE'],
    requiresConfirmation: true,
    requiresOperatorSession: true,
  },
  // query_control_tower
  {
    toolName: 'query_control_tower',
    label: 'Query Control Tower',
    description:
      'Reads Control Tower telemetry, deployment gates, and mission corrections to identify what needs fixing.',
    category: 'maintenance',
    targetTypes: ['generic'],
    riskLevel: 'safe_read',
    missionTypes: ['MAINTENANCE'],
    requiresConfirmation: false,
    requiresOperatorSession: true,
  },
  {
    toolName: 'detect_i18n_gaps',
    label: 'Detect i18n gaps',
    description: 'Scans dashboard src for hardcoded UI strings missing from i18n.js.',
    category: 'maintenance',
    targetTypes: ['generic'],
    riskLevel: 'safe_read',
    missionTypes: ['MAINTENANCE'],
    requiresConfirmation: false,
    requiresOperatorSession: true,
  },
  {
    toolName: 'apply_i18n_translations',
    label: 'Apply i18n translations',
    description: 'Translates detected gaps via Claude and merges keys into dashboard i18n.js.',
    category: 'maintenance',
    targetTypes: ['generic'],
    riskLevel: 'state_change',
    missionTypes: ['MAINTENANCE'],
    requiresConfirmation: true,
    requiresOperatorSession: true,
  },
];

const BY_NAME = new Map([...TOOLS, ...INTERNAL_MAINTENANCE_TOOLS].map((t) => [t.toolName, t]));

if (process.env.NODE_ENV !== 'production') {
  console.log(`[ToolRegistry] loaded tools: ${TOOLS.length}`);
}

/**
 * @param {string} toolName
 * @returns {{ toolName: string, label: string, description?: string, category: string, targetTypes: string[], requiresConfirmation: boolean } | undefined}
 */
export function getToolDefinition(toolName) {
  if (!toolName || typeof toolName !== 'string') return undefined;
  return BY_NAME.get(toolName.trim()) ?? undefined;
}

/**
 * @param {string} targetType
 * @returns {Array<{ toolName: string, label: string, description?: string, category: string, targetTypes: string[], requiresConfirmation: boolean }>}
 */
export function getToolsForTarget(targetType) {
  if (!targetType || typeof targetType !== 'string') return [];
  const t = targetType.trim();
  return TOOLS.filter((tool) => tool.targetTypes.includes(t));
}

/**
 * @param {string} category
 * @returns {Array<{ toolName: string, label: string, description?: string, category: string, targetTypes: string[], requiresConfirmation: boolean }>}
 */
export function getToolsForCategory(category) {
  if (!category || typeof category !== 'string') return [];
  const c = category.trim();
  return TOOLS.filter((tool) => tool.category === c);
}

/**
 * Tool list for LLM task planning (names must match dispatch / executors).
 * @returns {Array<{ toolName: string, label: string, description?: string, category: string, targetTypes: string[], planningHint: { agentHint: string } }>}
 */
export function getToolsForPlanner() {
  return TOOLS.map((t) => ({
    toolName: t.toolName,
    label: t.label,
    description: t.description,
    category: t.category,
    targetTypes: t.targetTypes,
    planningHint: { agentHint: 'dispatchTool' },
  }));
}

export { TOOLS };