/**
 * Reason codes for public storefront consumption cutover (Stage 4).
 */

export const STOREFRONT_CUTOVER_REASON_CODES = Object.freeze({
  STOREFRONT_LOCALIZATION_DISABLED_GLOBAL: 'STOREFRONT_LOCALIZATION_DISABLED_GLOBAL',
  STOREFRONT_LOCALIZATION_DISABLED_STORE: 'STOREFRONT_LOCALIZATION_DISABLED_STORE',
  STOREFRONT_LANGUAGE_UNSUPPORTED: 'STOREFRONT_LANGUAGE_UNSUPPORTED',
  STOREFRONT_TRANSLATION_NOT_FOUND: 'STOREFRONT_TRANSLATION_NOT_FOUND',
  STOREFRONT_TRANSLATION_STALE: 'STOREFRONT_TRANSLATION_STALE',
  STOREFRONT_TRANSLATION_INVALID: 'STOREFRONT_TRANSLATION_INVALID',
  STOREFRONT_CONSUMPTION_FAILED: 'STOREFRONT_CONSUMPTION_FAILED',
  STOREFRONT_CANONICAL_FALLBACK: 'STOREFRONT_CANONICAL_FALLBACK',
  STOREFRONT_LOCALIZED_RENDER_SELECTED: 'STOREFRONT_LOCALIZED_RENDER_SELECTED',
  STOREFRONT_MIXED_RENDER_SELECTED: 'STOREFRONT_MIXED_RENDER_SELECTED',
  STOREFRONT_SHADOW_COMPARISON: 'STOREFRONT_SHADOW_COMPARISON',
  STOREFRONT_ORIGINAL_MODE: 'STOREFRONT_ORIGINAL_MODE',
});
