/**
 * Default multi-agent alert rules (env thresholds override where noted).
 */

import { AlertChannel, AlertRule, AlertSeverity } from '../types/alert.types.js';

function envNum(key: string, fallback: number): number {
  const parsed = Number.parseFloat(process.env[key] ?? '');
  return Number.isFinite(parsed) ? parsed : fallback;
}

export function buildDefaultAlertRules(): AlertRule[] {
  return [
    {
      id: 'low_success_rate',
      name: 'Low Success Rate',
      description: 'Mission success rate dropped below threshold',
      severity: AlertSeverity.WARNING,
      condition: 'metrics.successRate',
      threshold: envNum('ALERT_SUCCESS_RATE_WARNING', 0.85),
      belowThreshold: true,
      window: 300,
      channels: [AlertChannel.SLACK, AlertChannel.WEBHOOK],
      cooldown: 600,
      enabled: true,
    },
    {
      id: 'critical_success_rate',
      name: 'Critical Success Rate',
      description: 'Mission success rate critically low',
      severity: AlertSeverity.CRITICAL,
      condition: 'metrics.successRate',
      threshold: envNum('ALERT_SUCCESS_RATE_CRITICAL', 0.7),
      belowThreshold: true,
      window: 300,
      channels: [AlertChannel.SLACK, AlertChannel.WEBHOOK, AlertChannel.PAGERDUTY],
      cooldown: 300,
      enabled: true,
    },
    {
      id: 'high_error_rate',
      name: 'High Error Rate',
      description: 'Error rate spiked above threshold',
      severity: AlertSeverity.WARNING,
      condition: 'metrics.errorRate',
      threshold: envNum('ALERT_ERROR_RATE_WARNING', 0.05),
      window: 300,
      channels: [AlertChannel.SLACK],
      cooldown: 600,
      enabled: true,
    },
    {
      id: 'critical_error_rate',
      name: 'Critical Error Rate',
      description: 'Error rate critically high',
      severity: AlertSeverity.CRITICAL,
      condition: 'metrics.errorRate',
      threshold: envNum('ALERT_ERROR_RATE_CRITICAL', 0.1),
      window: 300,
      channels: [AlertChannel.SLACK, AlertChannel.WEBHOOK, AlertChannel.PAGERDUTY],
      cooldown: 300,
      enabled: true,
    },
    {
      id: 'high_response_time',
      name: 'High Response Time',
      description: 'Average response time exceeded threshold',
      severity: AlertSeverity.WARNING,
      condition: 'metrics.averageResponseTime',
      threshold: envNum('ALERT_RESPONSE_TIME_WARNING', 5000),
      window: 300,
      channels: [AlertChannel.SLACK],
      cooldown: 600,
      enabled: true,
    },
    {
      id: 'critical_response_time',
      name: 'Critical Response Time',
      description: 'Response time critically high',
      severity: AlertSeverity.CRITICAL,
      condition: 'metrics.averageResponseTime',
      threshold: envNum('ALERT_RESPONSE_TIME_CRITICAL', 10000),
      window: 300,
      channels: [AlertChannel.SLACK, AlertChannel.WEBHOOK, AlertChannel.PAGERDUTY],
      cooldown: 300,
      enabled: true,
    },
    {
      id: 'high_cost_spike',
      name: 'High Cost Spike',
      description: 'Average cost per mission exceeded threshold',
      severity: AlertSeverity.WARNING,
      condition: 'metrics.averageCost',
      threshold: envNum('ALERT_COST_PER_MISSION_WARNING', 0.2),
      window: 3600,
      channels: [AlertChannel.SLACK],
      cooldown: 3600,
      enabled: true,
    },
    {
      id: 'hitl_rate_high',
      name: 'High HITL Rate',
      description: 'Human review escalation rate exceeded threshold',
      severity: AlertSeverity.WARNING,
      condition: 'metrics.hitlRate',
      threshold: envNum('ALERT_HITL_RATE_WARNING', 0.15),
      window: 3600,
      channels: [AlertChannel.SLACK],
      cooldown: 1800,
      enabled: true,
    },
    {
      id: 'shadow_accuracy_drop',
      name: 'Shadow Mode Accuracy Drop',
      description: 'DeepSeek shadow mode match rate decreased',
      severity: AlertSeverity.WARNING,
      condition: 'metrics.shadowMatchRate',
      threshold: envNum('ALERT_SHADOW_ACCURACY_WARNING', 0.8),
      belowThreshold: true,
      window: 3600,
      channels: [AlertChannel.SLACK],
      cooldown: 1800,
      enabled: true,
    },
    {
      id: 'high_memory_rss',
      name: 'High Memory RSS',
      description: 'Process RSS exceeded warning threshold',
      severity: AlertSeverity.WARNING,
      condition: 'process.rssMb',
      threshold: envNum('ALERT_MEMORY_THRESHOLD', 3000),
      window: 300,
      channels: [AlertChannel.SLACK, AlertChannel.WEBHOOK],
      cooldown: 600,
      enabled: true,
    },
    {
      id: 'critical_memory_rss',
      name: 'Critical Memory RSS',
      description: 'Process RSS exceeded critical threshold',
      severity: AlertSeverity.CRITICAL,
      condition: 'process.rssMb',
      threshold: envNum('ALERT_MEMORY_CRITICAL', 4000),
      window: 300,
      channels: [AlertChannel.SLACK, AlertChannel.WEBHOOK, AlertChannel.PAGERDUTY],
      cooldown: 300,
      enabled: true,
    },
    {
      id: 'stale_metrics',
      name: 'Stale Metrics Data',
      description: 'Multi-agent metrics have not been updated within freshness window',
      severity: AlertSeverity.WARNING,
      condition: 'metrics.updateAgeMs',
      threshold: envNum('MONITORING_FRESHNESS_MS', 300000),
      window: 300,
      channels: [AlertChannel.SLACK, AlertChannel.WEBHOOK],
      cooldown: 600,
      enabled: true,
    },
  ];
}

export const DEFAULT_ALERT_RULES = buildDefaultAlertRules();
