/** Contract version shared with dashboard menu-import client. */
export const MENU_IMPORT_CONTRACT_VERSION = '1';

export const MENU_IMPORT_FAILURE_CODES = Object.freeze({
  MENU_UPLOAD_TOO_LARGE: 'MENU_UPLOAD_TOO_LARGE',
  MENU_UPLOAD_UNSUPPORTED_TYPE: 'MENU_UPLOAD_UNSUPPORTED_TYPE',
  MENU_IMPORT_UNAUTHORIZED: 'MENU_IMPORT_UNAUTHORIZED',
  MENU_IMPORT_FORBIDDEN: 'MENU_IMPORT_FORBIDDEN',
  MENU_IMPORT_ROUTE_NOT_FOUND: 'MENU_IMPORT_ROUTE_NOT_FOUND',
  MENU_IMPORT_EXTRACTION_TIMEOUT: 'MENU_IMPORT_EXTRACTION_TIMEOUT',
  MENU_IMPORT_EXTRACTION_FAILED: 'MENU_IMPORT_EXTRACTION_FAILED',
  MENU_IMPORT_INVALID_RESPONSE: 'MENU_IMPORT_INVALID_RESPONSE',
  MENU_IMPORT_PERSISTENCE_FAILED: 'MENU_IMPORT_PERSISTENCE_FAILED',
  MENU_IMPORT_APPLY_FAILED: 'MENU_IMPORT_APPLY_FAILED',
  MENU_IMPORT_JOB_NOT_FOUND: 'MENU_IMPORT_JOB_NOT_FOUND',
  MENU_IMPORT_CONTRACT_MISMATCH: 'MENU_IMPORT_CONTRACT_MISMATCH',
});
