export const MARKET_INTENT_ANALYZER_VERSION = 'g1.1.0-demand-side';

export const MARKET_INTENT_FAMILIES = [
  'SELL',
  'BUY',
  'PROMOTE',
  'LAUNCH',
  'EXPAND',
  'PARTNER',
  'INVEST',
  'COLLABORATE',
  'HIRE',
  'SUPPLY',
  'DISTRIBUTE',
  'SOLVE_BUSINESS_PROBLEM',
  'OTHER_COMMERCIAL',
] as const;

export const HAS_CATEGORIES = [
  'PRODUCT',
  'SERVICE',
  'BUSINESS',
  'CAPABILITY',
  'ASSET',
  'CAPITAL',
  'LOCATION',
  'AUDIENCE',
  'KNOWLEDGE',
  'RELATIONSHIP',
  'OTHER',
] as const;

export const MARKET_ACTOR_ROLES = [
  'SUPPLIER',
  'BUYER',
  'CONSUMER',
  'DISTRIBUTOR',
  'RETAILER',
  'INVESTOR',
  'BUSINESS',
  'PARTNER',
  'CREATOR',
  'EMPLOYER',
  'TALENT',
  'INTERMEDIARY',
  'UNKNOWN',
] as const;

export const MARKET_SIDES = [
  'SUPPLY',
  'DEMAND',
  'INTERMEDIARY',
  'DUAL_SIDED',
  'UNKNOWN',
] as const;

export const WANTS_CATEGORIES = [
  'CUSTOMER',
  'BUYER',
  'SUPPLIER',
  'PARTNER',
  'INVESTOR',
  'CAPITAL',
  'DISTRIBUTOR',
  'RESELLER',
  'EMPLOYEE',
  'COLLABORATOR',
  'MARKET_ACCESS',
  'PROMOTION',
  'GROWTH',
  'SOLUTION',
  'OTHER',
] as const;
