/**
 * Constants for the Intent Reasoning Engine.
 */

import type { IntentReasonerConfig } from './intentTypes.js';

export const INTENT_REASONER_VERSION = '1.0.0';

export const INTENT_TYPE_LIST = [
  'create_store',
  'update_store',
  'publish_store',
  'view_store',
  'delete_store',
  'add_product',
  'update_product',
  'delete_product',
  'list_products',
  'import_products',
  'export_products',
  'create_campaign',
  'update_campaign',
  'launch_campaign',
  'view_campaign',
  'delete_campaign',
  'generate_graphic',
  'update_hero_image',
  'update_logo',
  'generate_promo_material',
  'create_catalog',
  'update_catalog',
  'view_catalog',
  'create_promotion',
  'update_promotion',
  'run_promotion',
  'upload_asset',
  'analyze_asset',
  'manage_assets',
  'view_analytics',
  'generate_report',
  'export_data',
  'setup_loyalty',
  'generate_content',
  'edit_content',
  'review_content',
  'search',
  'browse',
  'get_help',
  'general_chat',
  'clarification',
  'unknown',
  'guide_to_sign_in',
  'create_store_first',
  'select_store_first',
  'complete_workflow',
] as const;

export const INTENT_ACTION_TYPE_LIST = [
  'execute_tool',
  'guide_to_sign_in',
  'ask_clarification',
  'present_options',
  'continue_workflow',
  'start_new_workflow',
  'show_help',
  'complete_workflow',
  'cancel_workflow',
  'defer',
  'no_action',
] as const;

export const WORKFLOW_TYPE_LIST = [
  'store_creation',
  'campaign_creation',
  'graphic_generation',
  'product_management',
  'catalog_creation',
  'promotion_creation',
  'analytics',
  'content_generation',
  'asset_management',
  'unknown',
] as const;

export const DEFAULT_REASONER_CONFIG: IntentReasonerConfig = {
  minConfidenceThreshold: 0.7,
  minClarificationThreshold: 0.4,
  maxReasoningTimeMs: 2000,
  guestAwareEnabled: true,
  learningEnabled: true,
  traceEnabled: process.env.NODE_ENV === 'development',
  maxInteractions: 100,
  defaultAction: 'ask_clarification',
  supportedLanguages: ['en', 'vi'],
};

export const GUEST_GUIDANCE_DEFAULTS = {
  signInMessage: 'Sign in to save your progress and continue',
  alternativeMessage: 'Continue as guest (read-only)',
  lossWarning: "Your progress will be lost if you don't sign in",
  gainMessage: 'Sign in to save your store and add products',
} as const;

export const CONFIDENCE_LEVELS = {
  HIGH: 0.8,
  MEDIUM: 0.6,
  LOW: 0.4,
  VERY_LOW: 0.2,
} as const;

export const INTENT_DISPLAY_NAMES: Record<string, string> = {
  create_store: 'Create Store',
  update_store: 'Update Store',
  publish_store: 'Publish Store',
  view_store: 'View Store',
  delete_store: 'Delete Store',
  add_product: 'Add Product',
  update_product: 'Update Product',
  delete_product: 'Delete Product',
  list_products: 'List Products',
  import_products: 'Import Products',
  export_products: 'Export Products',
  create_campaign: 'Create Campaign',
  update_campaign: 'Update Campaign',
  launch_campaign: 'Launch Campaign',
  view_campaign: 'View Campaign',
  delete_campaign: 'Delete Campaign',
  generate_graphic: 'Generate Graphic',
  update_hero_image: 'Update Hero Image',
  update_logo: 'Update Logo',
  generate_promo_material: 'Generate Promo Material',
  create_catalog: 'Create Catalog',
  update_catalog: 'Update Catalog',
  view_catalog: 'View Catalog',
  create_promotion: 'Create Promotion',
  update_promotion: 'Update Promotion',
  run_promotion: 'Run Promotion',
  upload_asset: 'Upload Asset',
  analyze_asset: 'Analyze Asset',
  manage_assets: 'Manage Assets',
  view_analytics: 'View Analytics',
  setup_loyalty: 'Setup Loyalty Program',
  generate_report: 'Generate Report',
  export_data: 'Export Data',
  generate_content: 'Generate Content',
  edit_content: 'Edit Content',
  review_content: 'Review Content',
  search: 'Search',
  browse: 'Browse',
  get_help: 'Get Help',
  general_chat: 'General Chat',
  clarification: 'Clarification',
  unknown: 'Unknown Intent',
  guide_to_sign_in: 'Sign In Required',
  create_store_first: 'Create a Store First',
  select_store_first: 'Select a Store First',
  complete_workflow: 'Complete Workflow',
};
